// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/yanzhe/robomaster/recodaemon/net/proto/Image.proto

package org.yanzhe.robomaster.recodaemon.net.proto;

public final class ImageProto {
    static {
    }

    private ImageProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public interface ImageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:org.yanzhe.robomaster.recodaemon.net.proto.Image)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        boolean hasRows();

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        com.google.protobuf.Int32Value getRows();

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        boolean hasCols();

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        com.google.protobuf.Int32Value getCols();

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        boolean hasChannels();

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        com.google.protobuf.Int32Value getChannels();

        /**
         * <code>bytes data = 4;</code>
         */
        com.google.protobuf.ByteString getData();
    }

    /**
     * Protobuf type {@code org.yanzhe.robomaster.recodaemon.net.proto.Image}
     */
    public static final class Image extends
            com.google.protobuf.GeneratedMessageLite<
                    Image, Image.Builder> implements
            // @@protoc_insertion_point(message_implements:org.yanzhe.robomaster.recodaemon.net.proto.Image)
            ImageOrBuilder {
        public static final int ROWS_FIELD_NUMBER = 1;
        public static final int COLS_FIELD_NUMBER = 2;
        public static final int CHANNELS_FIELD_NUMBER = 3;
        public static final int DATA_FIELD_NUMBER = 4;
        // @@protoc_insertion_point(class_scope:org.yanzhe.robomaster.recodaemon.net.proto.Image)
        private static final org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image DEFAULT_INSTANCE;
        private static volatile com.google.protobuf.Parser<Image> PARSER;

        static {
            DEFAULT_INSTANCE = new Image();
            DEFAULT_INSTANCE.makeImmutable();
        }

        private com.google.protobuf.Int32Value rows_;
        private com.google.protobuf.Int32Value cols_;
        private com.google.protobuf.Int32Value channels_;
        private com.google.protobuf.ByteString data_;

        private Image() {
            data_ = com.google.protobuf.ByteString.EMPTY;
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }

        public static Builder newBuilder(org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image prototype) {
            return DEFAULT_INSTANCE.createBuilder(prototype);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Image> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        public boolean hasRows() {
            return rows_ != null;
        }

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        public com.google.protobuf.Int32Value getRows() {
            return rows_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : rows_;
        }

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        private void setRows(
                com.google.protobuf.Int32Value.Builder builderForValue) {
            rows_ = builderForValue.build();

        }

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        private void setRows(com.google.protobuf.Int32Value value) {
            if (value == null) {
                throw new NullPointerException();
            }
            rows_ = value;

        }

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        private void mergeRows(com.google.protobuf.Int32Value value) {
            if (rows_ != null &&
                    rows_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
                rows_ =
                        com.google.protobuf.Int32Value.newBuilder(rows_).mergeFrom(value).buildPartial();
            } else {
                rows_ = value;
            }

        }

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        private void clearRows() {
            rows_ = null;

        }

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        public boolean hasCols() {
            return cols_ != null;
        }

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        public com.google.protobuf.Int32Value getCols() {
            return cols_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : cols_;
        }

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        private void setCols(
                com.google.protobuf.Int32Value.Builder builderForValue) {
            cols_ = builderForValue.build();

        }

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        private void setCols(com.google.protobuf.Int32Value value) {
            if (value == null) {
                throw new NullPointerException();
            }
            cols_ = value;

        }

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        private void mergeCols(com.google.protobuf.Int32Value value) {
            if (cols_ != null &&
                    cols_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
                cols_ =
                        com.google.protobuf.Int32Value.newBuilder(cols_).mergeFrom(value).buildPartial();
            } else {
                cols_ = value;
            }

        }

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        private void clearCols() {
            cols_ = null;

        }

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        public boolean hasChannels() {
            return channels_ != null;
        }

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        public com.google.protobuf.Int32Value getChannels() {
            return channels_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : channels_;
        }

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        private void setChannels(
                com.google.protobuf.Int32Value.Builder builderForValue) {
            channels_ = builderForValue.build();

        }

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        private void setChannels(com.google.protobuf.Int32Value value) {
            if (value == null) {
                throw new NullPointerException();
            }
            channels_ = value;

        }

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        private void mergeChannels(com.google.protobuf.Int32Value value) {
            if (channels_ != null &&
                    channels_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
                channels_ =
                        com.google.protobuf.Int32Value.newBuilder(channels_).mergeFrom(value).buildPartial();
            } else {
                channels_ = value;
            }

        }

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        private void clearChannels() {
            channels_ = null;

        }

        /**
         * <code>bytes data = 4;</code>
         */
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        /**
         * <code>bytes data = 4;</code>
         */
        private void setData(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            data_ = value;
        }

        /**
         * <code>bytes data = 4;</code>
         */
        private void clearData() {

            data_ = getDefaultInstance().getData();
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (rows_ != null) {
                output.writeMessage(1, getRows());
            }
            if (cols_ != null) {
                output.writeMessage(2, getCols());
            }
            if (channels_ != null) {
                output.writeMessage(3, getChannels());
            }
            if (!data_.isEmpty()) {
                output.writeBytes(4, data_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (rows_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getRows());
            }
            if (cols_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getCols());
            }
            if (channels_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, getChannels());
            }
            if (!data_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, data_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
        protected final java.lang.Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                java.lang.Object arg0, java.lang.Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image();
                }
                case IS_INITIALIZED: {
                    return DEFAULT_INSTANCE;
                }
                case MAKE_IMMUTABLE: {
                    return null;
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case VISIT: {
                    Visitor visitor = (Visitor) arg0;
                    org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image other = (org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image) arg1;
                    rows_ = visitor.visitMessage(rows_, other.rows_);
                    cols_ = visitor.visitMessage(cols_, other.cols_);
                    channels_ = visitor.visitMessage(channels_, other.channels_);
                    data_ = visitor.visitByteString(data_ != com.google.protobuf.ByteString.EMPTY, data_,
                            other.data_ != com.google.protobuf.ByteString.EMPTY, other.data_);
                    if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                            .INSTANCE) {
                    }
                    return this;
                }
                case MERGE_FROM_STREAM: {
                    com.google.protobuf.CodedInputStream input =
                            (com.google.protobuf.CodedInputStream) arg0;
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                            (com.google.protobuf.ExtensionRegistryLite) arg1;
                    if (extensionRegistry == null) {
                        throw new java.lang.NullPointerException();
                    }
                    try {
                        boolean done = false;
                        while (!done) {
                            int tag = input.readTag();
                            switch (tag) {
                                case 0:
                                    done = true;
                                    break;
                                case 10: {
                                    com.google.protobuf.Int32Value.Builder subBuilder = null;
                                    if (rows_ != null) {
                                        subBuilder = rows_.toBuilder();
                                    }
                                    rows_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
                                    if (subBuilder != null) {
                                        subBuilder.mergeFrom(rows_);
                                        rows_ = subBuilder.buildPartial();
                                    }

                                    break;
                                }
                                case 18: {
                                    com.google.protobuf.Int32Value.Builder subBuilder = null;
                                    if (cols_ != null) {
                                        subBuilder = cols_.toBuilder();
                                    }
                                    cols_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
                                    if (subBuilder != null) {
                                        subBuilder.mergeFrom(cols_);
                                        cols_ = subBuilder.buildPartial();
                                    }

                                    break;
                                }
                                case 26: {
                                    com.google.protobuf.Int32Value.Builder subBuilder = null;
                                    if (channels_ != null) {
                                        subBuilder = channels_.toBuilder();
                                    }
                                    channels_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
                                    if (subBuilder != null) {
                                        subBuilder.mergeFrom(channels_);
                                        channels_ = subBuilder.buildPartial();
                                    }

                                    break;
                                }
                                case 34: {

                                    data_ = input.readBytes();
                                    break;
                                }
                                default: {
                                    if (!parseUnknownField(tag, input)) {
                                        done = true;
                                    }
                                    break;
                                }
                            }
                        }
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw new RuntimeException(e.setUnfinishedMessage(this));
                    } catch (java.io.IOException e) {
                        throw new RuntimeException(
                                new com.google.protobuf.InvalidProtocolBufferException(
                                        e.getMessage()).setUnfinishedMessage(this));
                    } finally {
                    }
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    if (PARSER == null) {
                        synchronized (org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.class) {
                            if (PARSER == null) {
                                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                            }
                        }
                    }
                    return PARSER;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }

        /**
         * Protobuf type {@code org.yanzhe.robomaster.recodaemon.net.proto.Image}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image, Builder> implements
                // @@protoc_insertion_point(builder_implements:org.yanzhe.robomaster.recodaemon.net.proto.Image)
                org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.ImageOrBuilder {
            // Construct using org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public boolean hasRows() {
                return instance.hasRows();
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public com.google.protobuf.Int32Value getRows() {
                return instance.getRows();
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public Builder setRows(
                    com.google.protobuf.Int32Value.Builder builderForValue) {
                copyOnWrite();
                instance.setRows(builderForValue);
                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public Builder setRows(com.google.protobuf.Int32Value value) {
                copyOnWrite();
                instance.setRows(value);
                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public Builder mergeRows(com.google.protobuf.Int32Value value) {
                copyOnWrite();
                instance.mergeRows(value);
                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public Builder clearRows() {
                copyOnWrite();
                instance.clearRows();
                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public boolean hasCols() {
                return instance.hasCols();
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public com.google.protobuf.Int32Value getCols() {
                return instance.getCols();
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public Builder setCols(
                    com.google.protobuf.Int32Value.Builder builderForValue) {
                copyOnWrite();
                instance.setCols(builderForValue);
                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public Builder setCols(com.google.protobuf.Int32Value value) {
                copyOnWrite();
                instance.setCols(value);
                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public Builder mergeCols(com.google.protobuf.Int32Value value) {
                copyOnWrite();
                instance.mergeCols(value);
                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public Builder clearCols() {
                copyOnWrite();
                instance.clearCols();
                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public boolean hasChannels() {
                return instance.hasChannels();
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public com.google.protobuf.Int32Value getChannels() {
                return instance.getChannels();
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public Builder setChannels(
                    com.google.protobuf.Int32Value.Builder builderForValue) {
                copyOnWrite();
                instance.setChannels(builderForValue);
                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public Builder setChannels(com.google.protobuf.Int32Value value) {
                copyOnWrite();
                instance.setChannels(value);
                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public Builder mergeChannels(com.google.protobuf.Int32Value value) {
                copyOnWrite();
                instance.mergeChannels(value);
                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public Builder clearChannels() {
                copyOnWrite();
                instance.clearChannels();
                return this;
            }

            /**
             * <code>bytes data = 4;</code>
             */
            public com.google.protobuf.ByteString getData() {
                return instance.getData();
            }

            /**
             * <code>bytes data = 4;</code>
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setData(value);
                return this;
            }

            /**
             * <code>bytes data = 4;</code>
             */
            public Builder clearData() {
                copyOnWrite();
                instance.clearData();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:org.yanzhe.robomaster.recodaemon.net.proto.Image)
        }
    }

    // @@protoc_insertion_point(outer_class_scope)
}
