// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Image.proto

package org.yanzhe.robomaster.recodaemon.net.proto;

public final class ImageProto {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Image_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Image_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\013Image.proto\022*org.yanzhe.robomaster.rec" +
                        "odaemon.net.proto\032\036google/protobuf/wrapp" +
                        "ers.proto\"\232\001\n\005Image\022)\n\004rows\030\001 \001(\0132\033.goog" +
                        "le.protobuf.Int32Value\022)\n\004cols\030\002 \001(\0132\033.g" +
                        "oogle.protobuf.Int32Value\022-\n\010channels\030\003 " +
                        "\001(\0132\033.google.protobuf.Int32Value\022\014\n\004data" +
                        "\030\004 \001(\014B=\n*org.yanzhe.robomaster.recodaem" +
                        "on.net.protoB\nImageProtoH\001\370\001\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.WrappersProto.getDescriptor(),
                        }, assigner);
        internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Image_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Image_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Image_descriptor,
                new java.lang.String[]{"Rows", "Cols", "Channels", "Data",});
        com.google.protobuf.WrappersProto.getDescriptor();
    }

    private ImageProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface ImageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:org.yanzhe.robomaster.recodaemon.net.proto.Image)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        boolean hasRows();

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        com.google.protobuf.Int32Value getRows();

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        com.google.protobuf.Int32ValueOrBuilder getRowsOrBuilder();

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        boolean hasCols();

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        com.google.protobuf.Int32Value getCols();

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        com.google.protobuf.Int32ValueOrBuilder getColsOrBuilder();

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        boolean hasChannels();

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        com.google.protobuf.Int32Value getChannels();

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        com.google.protobuf.Int32ValueOrBuilder getChannelsOrBuilder();

        /**
         * <code>bytes data = 4;</code>
         */
        com.google.protobuf.ByteString getData();
    }

    /**
     * Protobuf type {@code org.yanzhe.robomaster.recodaemon.net.proto.Image}
     */
    public static final class Image extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:org.yanzhe.robomaster.recodaemon.net.proto.Image)
            ImageOrBuilder {
        public static final int ROWS_FIELD_NUMBER = 1;
        public static final int COLS_FIELD_NUMBER = 2;
        public static final int CHANNELS_FIELD_NUMBER = 3;
        public static final int DATA_FIELD_NUMBER = 4;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:org.yanzhe.robomaster.recodaemon.net.proto.Image)
        private static final org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Image>
                PARSER = new com.google.protobuf.AbstractParser<Image>() {
            @java.lang.Override
            public Image parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Image(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image();
        }

        private com.google.protobuf.Int32Value rows_;
        private com.google.protobuf.Int32Value cols_;
        private com.google.protobuf.Int32Value channels_;
        private com.google.protobuf.ByteString data_;
        private byte memoizedIsInitialized = -1;

        // Use Image.newBuilder() to construct.
        private Image(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Image() {
            data_ = com.google.protobuf.ByteString.EMPTY;
        }

        private Image(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.Int32Value.Builder subBuilder = null;
                            if (rows_ != null) {
                                subBuilder = rows_.toBuilder();
                            }
                            rows_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(rows_);
                                rows_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 18: {
                            com.google.protobuf.Int32Value.Builder subBuilder = null;
                            if (cols_ != null) {
                                subBuilder = cols_.toBuilder();
                            }
                            cols_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(cols_);
                                cols_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 26: {
                            com.google.protobuf.Int32Value.Builder subBuilder = null;
                            if (channels_ != null) {
                                subBuilder = channels_.toBuilder();
                            }
                            channels_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(channels_);
                                channels_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 34: {

                            data_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Image_descriptor;
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Image> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Image_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.class, org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.Builder.class);
        }

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        public boolean hasRows() {
            return rows_ != null;
        }

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        public com.google.protobuf.Int32Value getRows() {
            return rows_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : rows_;
        }

        /**
         * <code>.google.protobuf.Int32Value rows = 1;</code>
         */
        public com.google.protobuf.Int32ValueOrBuilder getRowsOrBuilder() {
            return getRows();
        }

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        public boolean hasCols() {
            return cols_ != null;
        }

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        public com.google.protobuf.Int32Value getCols() {
            return cols_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : cols_;
        }

        /**
         * <code>.google.protobuf.Int32Value cols = 2;</code>
         */
        public com.google.protobuf.Int32ValueOrBuilder getColsOrBuilder() {
            return getCols();
        }

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        public boolean hasChannels() {
            return channels_ != null;
        }

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        public com.google.protobuf.Int32Value getChannels() {
            return channels_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : channels_;
        }

        /**
         * <code>.google.protobuf.Int32Value channels = 3;</code>
         */
        public com.google.protobuf.Int32ValueOrBuilder getChannelsOrBuilder() {
            return getChannels();
        }

        /**
         * <code>bytes data = 4;</code>
         */
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (rows_ != null) {
                output.writeMessage(1, getRows());
            }
            if (cols_ != null) {
                output.writeMessage(2, getCols());
            }
            if (channels_ != null) {
                output.writeMessage(3, getChannels());
            }
            if (!data_.isEmpty()) {
                output.writeBytes(4, data_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (rows_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getRows());
            }
            if (cols_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getCols());
            }
            if (channels_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, getChannels());
            }
            if (!data_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, data_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image)) {
                return super.equals(obj);
            }
            org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image other = (org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image) obj;

            boolean result = true;
            result = result && (hasRows() == other.hasRows());
            if (hasRows()) {
                result = result && getRows()
                        .equals(other.getRows());
            }
            result = result && (hasCols() == other.hasCols());
            if (hasCols()) {
                result = result && getCols()
                        .equals(other.getCols());
            }
            result = result && (hasChannels() == other.hasChannels());
            if (hasChannels()) {
                result = result && getChannels()
                        .equals(other.getChannels());
            }
            result = result && getData()
                    .equals(other.getData());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasRows()) {
                hash = (37 * hash) + ROWS_FIELD_NUMBER;
                hash = (53 * hash) + getRows().hashCode();
            }
            if (hasCols()) {
                hash = (37 * hash) + COLS_FIELD_NUMBER;
                hash = (53 * hash) + getCols().hashCode();
            }
            if (hasChannels()) {
                hash = (37 * hash) + CHANNELS_FIELD_NUMBER;
                hash = (53 * hash) + getChannels().hashCode();
            }
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Image> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code org.yanzhe.robomaster.recodaemon.net.proto.Image}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:org.yanzhe.robomaster.recodaemon.net.proto.Image)
                org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.ImageOrBuilder {
            private com.google.protobuf.Int32Value rows_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> rowsBuilder_;
            private com.google.protobuf.Int32Value cols_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> colsBuilder_;
            private com.google.protobuf.Int32Value channels_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> channelsBuilder_;
            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

            // Construct using org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Image_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Image_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.class, org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (rowsBuilder_ == null) {
                    rows_ = null;
                } else {
                    rows_ = null;
                    rowsBuilder_ = null;
                }
                if (colsBuilder_ == null) {
                    cols_ = null;
                } else {
                    cols_ = null;
                    colsBuilder_ = null;
                }
                if (channelsBuilder_ == null) {
                    channels_ = null;
                } else {
                    channels_ = null;
                    channelsBuilder_ = null;
                }
                data_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Image_descriptor;
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image getDefaultInstanceForType() {
                return org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.getDefaultInstance();
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image build() {
                org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image buildPartial() {
                org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image result = new org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image(this);
                if (rowsBuilder_ == null) {
                    result.rows_ = rows_;
                } else {
                    result.rows_ = rowsBuilder_.build();
                }
                if (colsBuilder_ == null) {
                    result.cols_ = cols_;
                } else {
                    result.cols_ = colsBuilder_.build();
                }
                if (channelsBuilder_ == null) {
                    result.channels_ = channels_;
                } else {
                    result.channels_ = channelsBuilder_.build();
                }
                result.data_ = data_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image) {
                    return mergeFrom((org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image other) {
                if (other == org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.getDefaultInstance())
                    return this;
                if (other.hasRows()) {
                    mergeRows(other.getRows());
                }
                if (other.hasCols()) {
                    mergeCols(other.getCols());
                }
                if (other.hasChannels()) {
                    mergeChannels(other.getChannels());
                }
                if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
                    setData(other.getData());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public boolean hasRows() {
                return rowsBuilder_ != null || rows_ != null;
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public com.google.protobuf.Int32Value getRows() {
                if (rowsBuilder_ == null) {
                    return rows_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : rows_;
                } else {
                    return rowsBuilder_.getMessage();
                }
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public Builder setRows(
                    com.google.protobuf.Int32Value.Builder builderForValue) {
                if (rowsBuilder_ == null) {
                    rows_ = builderForValue.build();
                    onChanged();
                } else {
                    rowsBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public Builder setRows(com.google.protobuf.Int32Value value) {
                if (rowsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    rows_ = value;
                    onChanged();
                } else {
                    rowsBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public Builder mergeRows(com.google.protobuf.Int32Value value) {
                if (rowsBuilder_ == null) {
                    if (rows_ != null) {
                        rows_ =
                                com.google.protobuf.Int32Value.newBuilder(rows_).mergeFrom(value).buildPartial();
                    } else {
                        rows_ = value;
                    }
                    onChanged();
                } else {
                    rowsBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public Builder clearRows() {
                if (rowsBuilder_ == null) {
                    rows_ = null;
                    onChanged();
                } else {
                    rows_ = null;
                    rowsBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public com.google.protobuf.Int32Value.Builder getRowsBuilder() {

                onChanged();
                return getRowsFieldBuilder().getBuilder();
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            public com.google.protobuf.Int32ValueOrBuilder getRowsOrBuilder() {
                if (rowsBuilder_ != null) {
                    return rowsBuilder_.getMessageOrBuilder();
                } else {
                    return rows_ == null ?
                            com.google.protobuf.Int32Value.getDefaultInstance() : rows_;
                }
            }

            /**
             * <code>.google.protobuf.Int32Value rows = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>
            getRowsFieldBuilder() {
                if (rowsBuilder_ == null) {
                    rowsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                            getRows(),
                            getParentForChildren(),
                            isClean());
                    rows_ = null;
                }
                return rowsBuilder_;
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public boolean hasCols() {
                return colsBuilder_ != null || cols_ != null;
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public com.google.protobuf.Int32Value getCols() {
                if (colsBuilder_ == null) {
                    return cols_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : cols_;
                } else {
                    return colsBuilder_.getMessage();
                }
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public Builder setCols(
                    com.google.protobuf.Int32Value.Builder builderForValue) {
                if (colsBuilder_ == null) {
                    cols_ = builderForValue.build();
                    onChanged();
                } else {
                    colsBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public Builder setCols(com.google.protobuf.Int32Value value) {
                if (colsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    cols_ = value;
                    onChanged();
                } else {
                    colsBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public Builder mergeCols(com.google.protobuf.Int32Value value) {
                if (colsBuilder_ == null) {
                    if (cols_ != null) {
                        cols_ =
                                com.google.protobuf.Int32Value.newBuilder(cols_).mergeFrom(value).buildPartial();
                    } else {
                        cols_ = value;
                    }
                    onChanged();
                } else {
                    colsBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public Builder clearCols() {
                if (colsBuilder_ == null) {
                    cols_ = null;
                    onChanged();
                } else {
                    cols_ = null;
                    colsBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public com.google.protobuf.Int32Value.Builder getColsBuilder() {

                onChanged();
                return getColsFieldBuilder().getBuilder();
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            public com.google.protobuf.Int32ValueOrBuilder getColsOrBuilder() {
                if (colsBuilder_ != null) {
                    return colsBuilder_.getMessageOrBuilder();
                } else {
                    return cols_ == null ?
                            com.google.protobuf.Int32Value.getDefaultInstance() : cols_;
                }
            }

            /**
             * <code>.google.protobuf.Int32Value cols = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>
            getColsFieldBuilder() {
                if (colsBuilder_ == null) {
                    colsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                            getCols(),
                            getParentForChildren(),
                            isClean());
                    cols_ = null;
                }
                return colsBuilder_;
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public boolean hasChannels() {
                return channelsBuilder_ != null || channels_ != null;
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public com.google.protobuf.Int32Value getChannels() {
                if (channelsBuilder_ == null) {
                    return channels_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : channels_;
                } else {
                    return channelsBuilder_.getMessage();
                }
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public Builder setChannels(
                    com.google.protobuf.Int32Value.Builder builderForValue) {
                if (channelsBuilder_ == null) {
                    channels_ = builderForValue.build();
                    onChanged();
                } else {
                    channelsBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public Builder setChannels(com.google.protobuf.Int32Value value) {
                if (channelsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    channels_ = value;
                    onChanged();
                } else {
                    channelsBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public Builder mergeChannels(com.google.protobuf.Int32Value value) {
                if (channelsBuilder_ == null) {
                    if (channels_ != null) {
                        channels_ =
                                com.google.protobuf.Int32Value.newBuilder(channels_).mergeFrom(value).buildPartial();
                    } else {
                        channels_ = value;
                    }
                    onChanged();
                } else {
                    channelsBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public Builder clearChannels() {
                if (channelsBuilder_ == null) {
                    channels_ = null;
                    onChanged();
                } else {
                    channels_ = null;
                    channelsBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public com.google.protobuf.Int32Value.Builder getChannelsBuilder() {

                onChanged();
                return getChannelsFieldBuilder().getBuilder();
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            public com.google.protobuf.Int32ValueOrBuilder getChannelsOrBuilder() {
                if (channelsBuilder_ != null) {
                    return channelsBuilder_.getMessageOrBuilder();
                } else {
                    return channels_ == null ?
                            com.google.protobuf.Int32Value.getDefaultInstance() : channels_;
                }
            }

            /**
             * <code>.google.protobuf.Int32Value channels = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>
            getChannelsFieldBuilder() {
                if (channelsBuilder_ == null) {
                    channelsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                            getChannels(),
                            getParentForChildren(),
                            isClean());
                    channels_ = null;
                }
                return channelsBuilder_;
            }

            /**
             * <code>bytes data = 4;</code>
             */
            public com.google.protobuf.ByteString getData() {
                return data_;
            }

            /**
             * <code>bytes data = 4;</code>
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                data_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes data = 4;</code>
             */
            public Builder clearData() {

                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:org.yanzhe.robomaster.recodaemon.net.proto.Image)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
