// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcMessage.proto

package org.yanzhe.robomaster.recodaemon.net.proto;

public final class RpcMessageProto {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020RpcMessage.proto\022*org.yanzhe.robomaste" +
                        "r.recodaemon.net.proto\032\036google/protobuf/" +
                        "wrappers.proto\032\031google/protobuf/any.prot" +
                        "o\"\212\001\n\nRpcRequest\022\020\n\010callerId\030\001 \001(\005\022F\n\006me" +
                        "thod\030\002 \001(\01626.org.yanzhe.robomaster.recod" +
                        "aemon.net.proto.RecoMethod\022\"\n\004data\030\003 \001(\013" +
                        "2\024.google.protobuf.Any\"\207\001\n\013RpcResponse\022\020" +
                        "\n\010callerId\030\001 \001(\005\022B\n\006status\030\002 \001(\01622.org.y" +
                        "anzhe.robomaster.recodaemon.net.proto.St" +
                        "atus\022\"\n\004data\030\003 \001(\0132\024.google.protobuf.Any" +
                        "*\341\001\n\006Status\022\013\n\007SUCCESS\020\000\022\024\n\020BAD_REQUEST_" +
                        "DATA\020\001\022\025\n\021BAD_REQUEST_PROTO\020\002\022\025\n\021SERVICE" +
                        "_NOT_FOUND\020\003\022\024\n\020METHOD_NOT_FOUND\020\004\022\r\n\tRP" +
                        "C_ERROR\020\005\022\016\n\nRPC_FAILED\020\006\022\031\n\025INVALID_REQ" +
                        "UEST_PROTO\020\007\022\026\n\022BAD_RESPONSE_PROTO\020\010\022\020\n\014" +
                        "UNKNOWN_HOST\020\t\022\014\n\010IO_ERROR\020\n*R\n\nRecoMeth" +
                        "od\022\030\n\024RECO_SIMPLE_HW_DIGIT\020\000\022\026\n\022RECO_FIR" +
                        "E_HW_DIGIT\020\001\022\022\n\016RECO_LED_DIGIT\020\002BB\n*org." +
                        "yanzhe.robomaster.recodaemon.net.protoB\017" +
                        "RpcMessageProtoH\001\370\001\001P\000b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.WrappersProto.getDescriptor(),
                                com.google.protobuf.AnyProto.getDescriptor(),
                        }, assigner);
        internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcRequest_descriptor,
                new java.lang.String[]{"CallerId", "Method", "Data",});
        internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcResponse_descriptor,
                new java.lang.String[]{"CallerId", "Status", "Data",});
        com.google.protobuf.WrappersProto.getDescriptor();
        com.google.protobuf.AnyProto.getDescriptor();
    }

    private RpcMessageProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    /**
     * Protobuf enum {@code org.yanzhe.robomaster.recodaemon.net.proto.Status}
     */
    public enum Status
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>SUCCESS = 0;</code>
         */
        SUCCESS(0),
        /**
         * <pre>
         * Server-side errors
         * </pre>
         * <p>
         * <code>BAD_REQUEST_DATA = 1;</code>
         */
        BAD_REQUEST_DATA(1),
        /**
         * <pre>
         * Server received bad request proto
         * </pre>
         * <p>
         * <code>BAD_REQUEST_PROTO = 2;</code>
         */
        BAD_REQUEST_PROTO(2),
        /**
         * <pre>
         * Service not found on server
         * </pre>
         * <p>
         * <code>SERVICE_NOT_FOUND = 3;</code>
         */
        SERVICE_NOT_FOUND(3),
        /**
         * <pre>
         * Method not found on server
         * </pre>
         * <p>
         * <code>METHOD_NOT_FOUND = 4;</code>
         */
        METHOD_NOT_FOUND(4),
        /**
         * <pre>
         * Rpc threw exception on server
         * </pre>
         * <p>
         * <code>RPC_ERROR = 5;</code>
         */
        RPC_ERROR(5),
        /**
         * <pre>
         * Rpc failed on server
         * </pre>
         * <p>
         * <code>RPC_FAILED = 6;</code>
         */
        RPC_FAILED(6),
        /**
         * <pre>
         * Client-side errors (these are returned by the client-side code)
         * </pre>
         * <p>
         * <code>INVALID_REQUEST_PROTO = 7;</code>
         */
        INVALID_REQUEST_PROTO(7),
        /**
         * <pre>
         * Server returned a bad response proto
         * </pre>
         * <p>
         * <code>BAD_RESPONSE_PROTO = 8;</code>
         */
        BAD_RESPONSE_PROTO(8),
        /**
         * <pre>
         * Could not find supplied host
         * </pre>
         * <p>
         * <code>UNKNOWN_HOST = 9;</code>
         */
        UNKNOWN_HOST(9),
        /**
         * <pre>
         * I/O error while communicating with server
         * </pre>
         * <p>
         * <code>IO_ERROR = 10;</code>
         */
        IO_ERROR(10),
        UNRECOGNIZED(-1),;

        /**
         * <code>SUCCESS = 0;</code>
         */
        public static final int SUCCESS_VALUE = 0;
        /**
         * <pre>
         * Server-side errors
         * </pre>
         * <p>
         * <code>BAD_REQUEST_DATA = 1;</code>
         */
        public static final int BAD_REQUEST_DATA_VALUE = 1;
        /**
         * <pre>
         * Server received bad request proto
         * </pre>
         * <p>
         * <code>BAD_REQUEST_PROTO = 2;</code>
         */
        public static final int BAD_REQUEST_PROTO_VALUE = 2;
        /**
         * <pre>
         * Service not found on server
         * </pre>
         * <p>
         * <code>SERVICE_NOT_FOUND = 3;</code>
         */
        public static final int SERVICE_NOT_FOUND_VALUE = 3;
        /**
         * <pre>
         * Method not found on server
         * </pre>
         * <p>
         * <code>METHOD_NOT_FOUND = 4;</code>
         */
        public static final int METHOD_NOT_FOUND_VALUE = 4;
        /**
         * <pre>
         * Rpc threw exception on server
         * </pre>
         * <p>
         * <code>RPC_ERROR = 5;</code>
         */
        public static final int RPC_ERROR_VALUE = 5;
        /**
         * <pre>
         * Rpc failed on server
         * </pre>
         * <p>
         * <code>RPC_FAILED = 6;</code>
         */
        public static final int RPC_FAILED_VALUE = 6;
        /**
         * <pre>
         * Client-side errors (these are returned by the client-side code)
         * </pre>
         * <p>
         * <code>INVALID_REQUEST_PROTO = 7;</code>
         */
        public static final int INVALID_REQUEST_PROTO_VALUE = 7;
        /**
         * <pre>
         * Server returned a bad response proto
         * </pre>
         * <p>
         * <code>BAD_RESPONSE_PROTO = 8;</code>
         */
        public static final int BAD_RESPONSE_PROTO_VALUE = 8;
        /**
         * <pre>
         * Could not find supplied host
         * </pre>
         * <p>
         * <code>UNKNOWN_HOST = 9;</code>
         */
        public static final int UNKNOWN_HOST_VALUE = 9;
        /**
         * <pre>
         * I/O error while communicating with server
         * </pre>
         * <p>
         * <code>IO_ERROR = 10;</code>
         */
        public static final int IO_ERROR_VALUE = 10;
        private static final com.google.protobuf.Internal.EnumLiteMap<
                Status> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<Status>() {
                    public Status findValueByNumber(int number) {
                        return Status.forNumber(number);
                    }
                };
        private static final Status[] VALUES = values();
        private final int value;

        Status(int value) {
            this.value = value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static Status valueOf(int value) {
            return forNumber(value);
        }

        public static Status forNumber(int value) {
            switch (value) {
                case 0:
                    return SUCCESS;
                case 1:
                    return BAD_REQUEST_DATA;
                case 2:
                    return BAD_REQUEST_PROTO;
                case 3:
                    return SERVICE_NOT_FOUND;
                case 4:
                    return METHOD_NOT_FOUND;
                case 5:
                    return RPC_ERROR;
                case 6:
                    return RPC_FAILED;
                case 7:
                    return INVALID_REQUEST_PROTO;
                case 8:
                    return BAD_RESPONSE_PROTO;
                case 9:
                    return UNKNOWN_HOST;
                case 10:
                    return IO_ERROR;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
            return internalValueMap;
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.getDescriptor().getEnumTypes().get(0);
        }

        public static Status valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        // @@protoc_insertion_point(enum_scope:org.yanzhe.robomaster.recodaemon.net.proto.Status)
    }

    /**
     * Protobuf enum {@code org.yanzhe.robomaster.recodaemon.net.proto.RecoMethod}
     */
    public enum RecoMethod
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>RECO_SIMPLE_HW_DIGIT = 0;</code>
         */
        RECO_SIMPLE_HW_DIGIT(0),
        /**
         * <code>RECO_FIRE_HW_DIGIT = 1;</code>
         */
        RECO_FIRE_HW_DIGIT(1),
        /**
         * <code>RECO_LED_DIGIT = 2;</code>
         */
        RECO_LED_DIGIT(2),
        UNRECOGNIZED(-1),;

        /**
         * <code>RECO_SIMPLE_HW_DIGIT = 0;</code>
         */
        public static final int RECO_SIMPLE_HW_DIGIT_VALUE = 0;
        /**
         * <code>RECO_FIRE_HW_DIGIT = 1;</code>
         */
        public static final int RECO_FIRE_HW_DIGIT_VALUE = 1;
        /**
         * <code>RECO_LED_DIGIT = 2;</code>
         */
        public static final int RECO_LED_DIGIT_VALUE = 2;
        private static final com.google.protobuf.Internal.EnumLiteMap<
                RecoMethod> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<RecoMethod>() {
                    public RecoMethod findValueByNumber(int number) {
                        return RecoMethod.forNumber(number);
                    }
                };
        private static final RecoMethod[] VALUES = values();
        private final int value;

        RecoMethod(int value) {
            this.value = value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static RecoMethod valueOf(int value) {
            return forNumber(value);
        }

        public static RecoMethod forNumber(int value) {
            switch (value) {
                case 0:
                    return RECO_SIMPLE_HW_DIGIT;
                case 1:
                    return RECO_FIRE_HW_DIGIT;
                case 2:
                    return RECO_LED_DIGIT;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<RecoMethod>
        internalGetValueMap() {
            return internalValueMap;
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.getDescriptor().getEnumTypes().get(1);
        }

        public static RecoMethod valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        // @@protoc_insertion_point(enum_scope:org.yanzhe.robomaster.recodaemon.net.proto.RecoMethod)
    }

    public interface RpcRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:org.yanzhe.robomaster.recodaemon.net.proto.RpcRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 callerId = 1;</code>
         */
        int getCallerId();

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.RecoMethod method = 2;</code>
         */
        int getMethodValue();

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.RecoMethod method = 2;</code>
         */
        org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RecoMethod getMethod();

        /**
         * <code>.google.protobuf.Any data = 3;</code>
         */
        boolean hasData();

        /**
         * <code>.google.protobuf.Any data = 3;</code>
         */
        com.google.protobuf.Any getData();

        /**
         * <code>.google.protobuf.Any data = 3;</code>
         */
        com.google.protobuf.AnyOrBuilder getDataOrBuilder();
    }

    public interface RpcResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:org.yanzhe.robomaster.recodaemon.net.proto.RpcResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 callerId = 1;</code>
         */
        int getCallerId();

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Status status = 2;</code>
         */
        int getStatusValue();

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Status status = 2;</code>
         */
        org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.Status getStatus();

        /**
         * <code>.google.protobuf.Any data = 3;</code>
         */
        boolean hasData();

        /**
         * <code>.google.protobuf.Any data = 3;</code>
         */
        com.google.protobuf.Any getData();

        /**
         * <code>.google.protobuf.Any data = 3;</code>
         */
        com.google.protobuf.AnyOrBuilder getDataOrBuilder();
    }

    /**
     * Protobuf type {@code org.yanzhe.robomaster.recodaemon.net.proto.RpcRequest}
     */
    public static final class RpcRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:org.yanzhe.robomaster.recodaemon.net.proto.RpcRequest)
            RpcRequestOrBuilder {
        public static final int CALLERID_FIELD_NUMBER = 1;
        public static final int METHOD_FIELD_NUMBER = 2;
        public static final int DATA_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:org.yanzhe.robomaster.recodaemon.net.proto.RpcRequest)
        private static final org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<RpcRequest>
                PARSER = new com.google.protobuf.AbstractParser<RpcRequest>() {
            @java.lang.Override
            public RpcRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new RpcRequest(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest();
        }

        private int callerId_;
        private int method_;
        private com.google.protobuf.Any data_;
        private byte memoizedIsInitialized = -1;

        // Use RpcRequest.newBuilder() to construct.
        private RpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private RpcRequest() {
            callerId_ = 0;
            method_ = 0;
        }

        private RpcRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            callerId_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();

                            method_ = rawValue;
                            break;
                        }
                        case 26: {
                            com.google.protobuf.Any.Builder subBuilder = null;
                            if (data_ != null) {
                                subBuilder = data_.toBuilder();
                            }
                            data_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(data_);
                                data_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcRequest_descriptor;
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<RpcRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest.class, org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest.Builder.class);
        }

        /**
         * <code>int32 callerId = 1;</code>
         */
        public int getCallerId() {
            return callerId_;
        }

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.RecoMethod method = 2;</code>
         */
        public int getMethodValue() {
            return method_;
        }

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.RecoMethod method = 2;</code>
         */
        public org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RecoMethod getMethod() {
            @SuppressWarnings("deprecation")
            org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RecoMethod result = org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RecoMethod.valueOf(method_);
            return result == null ? org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RecoMethod.UNRECOGNIZED : result;
        }

        /**
         * <code>.google.protobuf.Any data = 3;</code>
         */
        public boolean hasData() {
            return data_ != null;
        }

        /**
         * <code>.google.protobuf.Any data = 3;</code>
         */
        public com.google.protobuf.Any getData() {
            return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        }

        /**
         * <code>.google.protobuf.Any data = 3;</code>
         */
        public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
            return getData();
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (callerId_ != 0) {
                output.writeInt32(1, callerId_);
            }
            if (method_ != org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RecoMethod.RECO_SIMPLE_HW_DIGIT.getNumber()) {
                output.writeEnum(2, method_);
            }
            if (data_ != null) {
                output.writeMessage(3, getData());
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (callerId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, callerId_);
            }
            if (method_ != org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RecoMethod.RECO_SIMPLE_HW_DIGIT.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, method_);
            }
            if (data_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, getData());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest)) {
                return super.equals(obj);
            }
            org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest other = (org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest) obj;

            boolean result = true;
            result = result && (getCallerId()
                    == other.getCallerId());
            result = result && method_ == other.method_;
            result = result && (hasData() == other.hasData());
            if (hasData()) {
                result = result && getData()
                        .equals(other.getData());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CALLERID_FIELD_NUMBER;
            hash = (53 * hash) + getCallerId();
            hash = (37 * hash) + METHOD_FIELD_NUMBER;
            hash = (53 * hash) + method_;
            if (hasData()) {
                hash = (37 * hash) + DATA_FIELD_NUMBER;
                hash = (53 * hash) + getData().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RpcRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code org.yanzhe.robomaster.recodaemon.net.proto.RpcRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:org.yanzhe.robomaster.recodaemon.net.proto.RpcRequest)
                org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequestOrBuilder {
            private int callerId_;
            private int method_ = 0;
            private com.google.protobuf.Any data_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;

            // Construct using org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest.class, org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                callerId_ = 0;

                method_ = 0;

                if (dataBuilder_ == null) {
                    data_ = null;
                } else {
                    data_ = null;
                    dataBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcRequest_descriptor;
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest getDefaultInstanceForType() {
                return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest.getDefaultInstance();
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest build() {
                org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest buildPartial() {
                org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest result = new org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest(this);
                result.callerId_ = callerId_;
                result.method_ = method_;
                if (dataBuilder_ == null) {
                    result.data_ = data_;
                } else {
                    result.data_ = dataBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest) {
                    return mergeFrom((org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest other) {
                if (other == org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest.getDefaultInstance())
                    return this;
                if (other.getCallerId() != 0) {
                    setCallerId(other.getCallerId());
                }
                if (other.method_ != 0) {
                    setMethodValue(other.getMethodValue());
                }
                if (other.hasData()) {
                    mergeData(other.getData());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>int32 callerId = 1;</code>
             */
            public int getCallerId() {
                return callerId_;
            }

            /**
             * <code>int32 callerId = 1;</code>
             */
            public Builder setCallerId(int value) {

                callerId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 callerId = 1;</code>
             */
            public Builder clearCallerId() {

                callerId_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.RecoMethod method = 2;</code>
             */
            public int getMethodValue() {
                return method_;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.RecoMethod method = 2;</code>
             */
            public Builder setMethodValue(int value) {
                method_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.RecoMethod method = 2;</code>
             */
            public org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RecoMethod getMethod() {
                @SuppressWarnings("deprecation")
                org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RecoMethod result = org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RecoMethod.valueOf(method_);
                return result == null ? org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RecoMethod.UNRECOGNIZED : result;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.RecoMethod method = 2;</code>
             */
            public Builder setMethod(org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RecoMethod value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                method_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.RecoMethod method = 2;</code>
             */
            public Builder clearMethod() {

                method_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public boolean hasData() {
                return dataBuilder_ != null || data_ != null;
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public com.google.protobuf.Any getData() {
                if (dataBuilder_ == null) {
                    return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
                } else {
                    return dataBuilder_.getMessage();
                }
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public Builder setData(
                    com.google.protobuf.Any.Builder builderForValue) {
                if (dataBuilder_ == null) {
                    data_ = builderForValue.build();
                    onChanged();
                } else {
                    dataBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public Builder setData(com.google.protobuf.Any value) {
                if (dataBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    data_ = value;
                    onChanged();
                } else {
                    dataBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public Builder mergeData(com.google.protobuf.Any value) {
                if (dataBuilder_ == null) {
                    if (data_ != null) {
                        data_ =
                                com.google.protobuf.Any.newBuilder(data_).mergeFrom(value).buildPartial();
                    } else {
                        data_ = value;
                    }
                    onChanged();
                } else {
                    dataBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public Builder clearData() {
                if (dataBuilder_ == null) {
                    data_ = null;
                    onChanged();
                } else {
                    data_ = null;
                    dataBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public com.google.protobuf.Any.Builder getDataBuilder() {

                onChanged();
                return getDataFieldBuilder().getBuilder();
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
                if (dataBuilder_ != null) {
                    return dataBuilder_.getMessageOrBuilder();
                } else {
                    return data_ == null ?
                            com.google.protobuf.Any.getDefaultInstance() : data_;
                }
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>
            getDataFieldBuilder() {
                if (dataBuilder_ == null) {
                    dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                            getData(),
                            getParentForChildren(),
                            isClean());
                    data_ = null;
                }
                return dataBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:org.yanzhe.robomaster.recodaemon.net.proto.RpcRequest)
        }

    }

    /**
     * Protobuf type {@code org.yanzhe.robomaster.recodaemon.net.proto.RpcResponse}
     */
    public static final class RpcResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:org.yanzhe.robomaster.recodaemon.net.proto.RpcResponse)
            RpcResponseOrBuilder {
        public static final int CALLERID_FIELD_NUMBER = 1;
        public static final int STATUS_FIELD_NUMBER = 2;
        public static final int DATA_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:org.yanzhe.robomaster.recodaemon.net.proto.RpcResponse)
        private static final org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<RpcResponse>
                PARSER = new com.google.protobuf.AbstractParser<RpcResponse>() {
            @java.lang.Override
            public RpcResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new RpcResponse(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse();
        }

        private int callerId_;
        private int status_;
        private com.google.protobuf.Any data_;
        private byte memoizedIsInitialized = -1;

        // Use RpcResponse.newBuilder() to construct.
        private RpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private RpcResponse() {
            callerId_ = 0;
            status_ = 0;
        }

        private RpcResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            callerId_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();

                            status_ = rawValue;
                            break;
                        }
                        case 26: {
                            com.google.protobuf.Any.Builder subBuilder = null;
                            if (data_ != null) {
                                subBuilder = data_.toBuilder();
                            }
                            data_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(data_);
                                data_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcResponse_descriptor;
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<RpcResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse.class, org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse.Builder.class);
        }

        /**
         * <code>int32 callerId = 1;</code>
         */
        public int getCallerId() {
            return callerId_;
        }

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Status status = 2;</code>
         */
        public int getStatusValue() {
            return status_;
        }

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Status status = 2;</code>
         */
        public org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.Status getStatus() {
            @SuppressWarnings("deprecation")
            org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.Status result = org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.Status.valueOf(status_);
            return result == null ? org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.Status.UNRECOGNIZED : result;
        }

        /**
         * <code>.google.protobuf.Any data = 3;</code>
         */
        public boolean hasData() {
            return data_ != null;
        }

        /**
         * <code>.google.protobuf.Any data = 3;</code>
         */
        public com.google.protobuf.Any getData() {
            return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        }

        /**
         * <code>.google.protobuf.Any data = 3;</code>
         */
        public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
            return getData();
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (callerId_ != 0) {
                output.writeInt32(1, callerId_);
            }
            if (status_ != org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.Status.SUCCESS.getNumber()) {
                output.writeEnum(2, status_);
            }
            if (data_ != null) {
                output.writeMessage(3, getData());
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (callerId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, callerId_);
            }
            if (status_ != org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.Status.SUCCESS.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, status_);
            }
            if (data_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, getData());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse)) {
                return super.equals(obj);
            }
            org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse other = (org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse) obj;

            boolean result = true;
            result = result && (getCallerId()
                    == other.getCallerId());
            result = result && status_ == other.status_;
            result = result && (hasData() == other.hasData());
            if (hasData()) {
                result = result && getData()
                        .equals(other.getData());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CALLERID_FIELD_NUMBER;
            hash = (53 * hash) + getCallerId();
            hash = (37 * hash) + STATUS_FIELD_NUMBER;
            hash = (53 * hash) + status_;
            if (hasData()) {
                hash = (37 * hash) + DATA_FIELD_NUMBER;
                hash = (53 * hash) + getData().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RpcResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code org.yanzhe.robomaster.recodaemon.net.proto.RpcResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:org.yanzhe.robomaster.recodaemon.net.proto.RpcResponse)
                org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponseOrBuilder {
            private int callerId_;
            private int status_ = 0;
            private com.google.protobuf.Any data_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;

            // Construct using org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse.class, org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                callerId_ = 0;

                status_ = 0;

                if (dataBuilder_ == null) {
                    data_ = null;
                } else {
                    data_ = null;
                    dataBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_RpcResponse_descriptor;
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse getDefaultInstanceForType() {
                return org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse.getDefaultInstance();
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse build() {
                org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse buildPartial() {
                org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse result = new org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse(this);
                result.callerId_ = callerId_;
                result.status_ = status_;
                if (dataBuilder_ == null) {
                    result.data_ = data_;
                } else {
                    result.data_ = dataBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse) {
                    return mergeFrom((org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse other) {
                if (other == org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse.getDefaultInstance())
                    return this;
                if (other.getCallerId() != 0) {
                    setCallerId(other.getCallerId());
                }
                if (other.status_ != 0) {
                    setStatusValue(other.getStatusValue());
                }
                if (other.hasData()) {
                    mergeData(other.getData());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.RpcResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>int32 callerId = 1;</code>
             */
            public int getCallerId() {
                return callerId_;
            }

            /**
             * <code>int32 callerId = 1;</code>
             */
            public Builder setCallerId(int value) {

                callerId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 callerId = 1;</code>
             */
            public Builder clearCallerId() {

                callerId_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Status status = 2;</code>
             */
            public int getStatusValue() {
                return status_;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Status status = 2;</code>
             */
            public Builder setStatusValue(int value) {
                status_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Status status = 2;</code>
             */
            public org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.Status getStatus() {
                @SuppressWarnings("deprecation")
                org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.Status result = org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.Status.valueOf(status_);
                return result == null ? org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.Status.UNRECOGNIZED : result;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Status status = 2;</code>
             */
            public Builder setStatus(org.yanzhe.robomaster.recodaemon.net.proto.RpcMessageProto.Status value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                status_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Status status = 2;</code>
             */
            public Builder clearStatus() {

                status_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public boolean hasData() {
                return dataBuilder_ != null || data_ != null;
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public com.google.protobuf.Any getData() {
                if (dataBuilder_ == null) {
                    return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
                } else {
                    return dataBuilder_.getMessage();
                }
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public Builder setData(
                    com.google.protobuf.Any.Builder builderForValue) {
                if (dataBuilder_ == null) {
                    data_ = builderForValue.build();
                    onChanged();
                } else {
                    dataBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public Builder setData(com.google.protobuf.Any value) {
                if (dataBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    data_ = value;
                    onChanged();
                } else {
                    dataBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public Builder mergeData(com.google.protobuf.Any value) {
                if (dataBuilder_ == null) {
                    if (data_ != null) {
                        data_ =
                                com.google.protobuf.Any.newBuilder(data_).mergeFrom(value).buildPartial();
                    } else {
                        data_ = value;
                    }
                    onChanged();
                } else {
                    dataBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public Builder clearData() {
                if (dataBuilder_ == null) {
                    data_ = null;
                    onChanged();
                } else {
                    data_ = null;
                    dataBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public com.google.protobuf.Any.Builder getDataBuilder() {

                onChanged();
                return getDataFieldBuilder().getBuilder();
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
                if (dataBuilder_ != null) {
                    return dataBuilder_.getMessageOrBuilder();
                } else {
                    return data_ == null ?
                            com.google.protobuf.Any.getDefaultInstance() : data_;
                }
            }

            /**
             * <code>.google.protobuf.Any data = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>
            getDataFieldBuilder() {
                if (dataBuilder_ == null) {
                    dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                            getData(),
                            getParentForChildren(),
                            isClean());
                    data_ = null;
                }
                return dataBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:org.yanzhe.robomaster.recodaemon.net.proto.RpcResponse)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
