// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TargetCells.proto

package org.yanzhe.robomaster.recodaemon.net.proto;

public final class TargetCellsProto {
  private TargetCellsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_yanzhe_robomaster_recodaemon_net_proto_TargetCells_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_org_yanzhe_robomaster_recodaemon_net_proto_TargetCells_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Cell_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Cell_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\021TargetCells.proto\022*org.yanzhe.robomast" +
                        "er.recodaemon.net.proto\032\036google/protobuf" +
                        "/wrappers.proto\032\013Image.proto\"N\n\013TargetCe" +
                        "lls\022?\n\005cells\030\002 \003(\01320.org.yanzhe.robomast" +
                        "er.recodaemon.net.proto.Cell\"\307\001\n\004Cell\022)\n" +
                        "\003seq\030\001 \001(\0132\034.google.protobuf.UInt64Value" +
                        "\022*\n\004goal\030\002 \001(\0132\034.google.protobuf.UInt32V" +
                        "alue\022(\n\003pos\030\003 \001(\0132\033.google.protobuf.Int3" +
                        "2Value\022>\n\003img\030\004 \001(\01321.org.yanzhe.robomas" +
                        "ter.recodaemon.net.proto.ImageBC\n*org.ya" +
                        "nzhe.robomaster.recodaemon.net.protoB\020Ta" +
                        "rgetCellsProtoH\001\370\001\001P\000P\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.WrappersProto.getDescriptor(),
                                org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.getDescriptor(),
                        }, assigner);
        internal_static_org_yanzhe_robomaster_recodaemon_net_proto_TargetCells_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_org_yanzhe_robomaster_recodaemon_net_proto_TargetCells_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_org_yanzhe_robomaster_recodaemon_net_proto_TargetCells_descriptor,
                new java.lang.String[]{"Cells",});
        internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Cell_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Cell_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Cell_descriptor,
                new java.lang.String[]{"Seq", "Goal", "Pos", "Img",});
        com.google.protobuf.WrappersProto.getDescriptor();
        org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.getDescriptor();
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
  }

    public interface TargetCellsOrBuilder extends
            // @@protoc_insertion_point(interface_extends:org.yanzhe.robomaster.recodaemon.net.proto.TargetCells)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         *    RecoMethod method = 1;
         * </pre>
         *
         * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
         */
        java.util.List<org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell>
        getCellsList();

        /**
         * <pre>
         *    RecoMethod method = 1;
         * </pre>
         *
         * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
         */
        org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell getCells(int index);

        /**
         * <pre>
         *    RecoMethod method = 1;
         * </pre>
         *
         * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
         */
        int getCellsCount();

        /**
         * <pre>
         *    RecoMethod method = 1;
         * </pre>
         * <p>
         * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
         */
        java.util.List<? extends org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.CellOrBuilder>
        getCellsOrBuilderList();

        /**
         * <pre>
         *    RecoMethod method = 1;
         * </pre>
         * <p>
         * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
         */
        org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.CellOrBuilder getCellsOrBuilder(
                int index);
    }

    public interface CellOrBuilder extends
            // @@protoc_insertion_point(interface_extends:org.yanzhe.robomaster.recodaemon.net.proto.Cell)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.google.protobuf.UInt64Value seq = 1;</code>
         */
        boolean hasSeq();

        /**
         * <code>.google.protobuf.UInt64Value seq = 1;</code>
         */
        com.google.protobuf.UInt64Value getSeq();

        /**
         * <code>.google.protobuf.UInt64Value seq = 1;</code>
         */
        com.google.protobuf.UInt64ValueOrBuilder getSeqOrBuilder();

        /**
         * <code>.google.protobuf.UInt32Value goal = 2;</code>
         */
        boolean hasGoal();

        /**
         * <code>.google.protobuf.UInt32Value goal = 2;</code>
         */
        com.google.protobuf.UInt32Value getGoal();

        /**
         * <code>.google.protobuf.UInt32Value goal = 2;</code>
         */
        com.google.protobuf.UInt32ValueOrBuilder getGoalOrBuilder();

        /**
         * <code>.google.protobuf.Int32Value pos = 3;</code>
         */
        boolean hasPos();

        /**
         * <code>.google.protobuf.Int32Value pos = 3;</code>
         */
        com.google.protobuf.Int32Value getPos();

        /**
         * <code>.google.protobuf.Int32Value pos = 3;</code>
         */
        com.google.protobuf.Int32ValueOrBuilder getPosOrBuilder();

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
         */
        boolean hasImg();

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
         */
        org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image getImg();

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
         */
        org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.ImageOrBuilder getImgOrBuilder();
    }

    /**
     * Protobuf type {@code org.yanzhe.robomaster.recodaemon.net.proto.TargetCells}
     */
    public static final class TargetCells extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:org.yanzhe.robomaster.recodaemon.net.proto.TargetCells)
      TargetCellsOrBuilder {
  private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:org.yanzhe.robomaster.recodaemon.net.proto.TargetCells)
    private static final org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<TargetCells>
                PARSER = new com.google.protobuf.AbstractParser<TargetCells>() {
            @java.lang.Override
            public TargetCells parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TargetCells(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells();
        }

        private java.util.List<org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell> cells_;
        private byte memoizedIsInitialized = -1;

        // Use TargetCells.newBuilder() to construct.
        private TargetCells(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        public static final int CELLS_FIELD_NUMBER = 2;

        private TargetCells() {
            cells_ = java.util.Collections.emptyList();
        }

        private TargetCells(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 18: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                cells_ = new java.util.ArrayList<org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            cells_.add(
                                    input.readMessage(org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.parser(), extensionRegistry));
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    cells_ = java.util.Collections.unmodifiableList(cells_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_TargetCells_descriptor;
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
                com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

        public static Builder newBuilder(org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

        public static com.google.protobuf.Parser<TargetCells> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_TargetCells_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.class, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Builder.class);
        }

        /**
     * <pre>
         *    RecoMethod method = 1;
         * </pre>
         *
         * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
         */
        public java.util.List<org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell> getCellsList() {
            return cells_;
        }

        /**
     * <pre>
         *    RecoMethod method = 1;
         * </pre>
         *
         * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
     */
    public java.util.List<? extends org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.CellOrBuilder>
    getCellsOrBuilderList() {
        return cells_;
    }

        /**
     * <pre>
     *    RecoMethod method = 1;
     * </pre>
     *
     * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
         */
        public int getCellsCount() {
            return cells_.size();
        }

        /**
     * <pre>
         *    RecoMethod method = 1;
         * </pre>
         *
         * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
         */
        public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell getCells(int index) {
            return cells_.get(index);
        }

        /**
     * <pre>
         *    RecoMethod method = 1;
         * </pre>
         *
         * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
     */
    public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.CellOrBuilder getCellsOrBuilder(
            int index) {
        return cells_.get(index);
    }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < cells_.size(); i++) {
                output.writeMessage(2, cells_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < cells_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, cells_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells)) {
                return super.equals(obj);
            }
            org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells other = (org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells) obj;

            boolean result = true;
            result = result && getCellsList()
                    .equals(other.getCellsList());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getCellsCount() > 0) {
                hash = (37 * hash) + CELLS_FIELD_NUMBER;
                hash = (53 * hash) + getCellsList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<TargetCells> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code org.yanzhe.robomaster.recodaemon.net.proto.TargetCells}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:org.yanzhe.robomaster.recodaemon.net.proto.TargetCells)
                org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCellsOrBuilder {
            private int bitField0_;
            private java.util.List<org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell> cells_ =
                    java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.Builder, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.CellOrBuilder> cellsBuilder_;

            // Construct using org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_TargetCells_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_TargetCells_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.class, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getCellsFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (cellsBuilder_ == null) {
                    cells_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    cellsBuilder_.clear();
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_TargetCells_descriptor;
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells getDefaultInstanceForType() {
                return org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.getDefaultInstance();
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells build() {
                org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells buildPartial() {
                org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells result = new org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells(this);
                int from_bitField0_ = bitField0_;
                if (cellsBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        cells_ = java.util.Collections.unmodifiableList(cells_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.cells_ = cells_;
                } else {
                    result.cells_ = cellsBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells) {
                    return mergeFrom((org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells other) {
                if (other == org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.getDefaultInstance())
                    return this;
                if (cellsBuilder_ == null) {
                    if (!other.cells_.isEmpty()) {
                        if (cells_.isEmpty()) {
                            cells_ = other.cells_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureCellsIsMutable();
                            cells_.addAll(other.cells_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.cells_.isEmpty()) {
                        if (cellsBuilder_.isEmpty()) {
                            cellsBuilder_.dispose();
                            cellsBuilder_ = null;
                            cells_ = other.cells_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            cellsBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getCellsFieldBuilder() : null;
                        } else {
                            cellsBuilder_.addAllMessages(other.cells_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private void ensureCellsIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    cells_ = new java.util.ArrayList<org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell>(cells_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             *
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public java.util.List<org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell> getCellsList() {
                if (cellsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(cells_);
                } else {
                    return cellsBuilder_.getMessageList();
                }
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             *
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public int getCellsCount() {
                if (cellsBuilder_ == null) {
                    return cells_.size();
                } else {
                    return cellsBuilder_.getCount();
                }
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             *
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell getCells(int index) {
                if (cellsBuilder_ == null) {
                    return cells_.get(index);
                } else {
                    return cellsBuilder_.getMessage(index);
                }
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             *
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public Builder setCells(
                    int index, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell value) {
                if (cellsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCellsIsMutable();
                    cells_.set(index, value);
                    onChanged();
                } else {
                    cellsBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             *
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public Builder setCells(
                    int index, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.Builder builderForValue) {
                if (cellsBuilder_ == null) {
                    ensureCellsIsMutable();
                    cells_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    cellsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             *
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public Builder addCells(org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell value) {
                if (cellsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCellsIsMutable();
                    cells_.add(value);
                    onChanged();
                } else {
                    cellsBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             *
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public Builder addCells(
                    int index, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell value) {
                if (cellsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCellsIsMutable();
                    cells_.add(index, value);
                    onChanged();
                } else {
                    cellsBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             *
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public Builder addCells(
                    org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.Builder builderForValue) {
                if (cellsBuilder_ == null) {
                    ensureCellsIsMutable();
                    cells_.add(builderForValue.build());
                    onChanged();
                } else {
                    cellsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             *
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public Builder addCells(
                    int index, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.Builder builderForValue) {
                if (cellsBuilder_ == null) {
                    ensureCellsIsMutable();
                    cells_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    cellsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             *
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public Builder addAllCells(
                    java.lang.Iterable<? extends org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell> values) {
                if (cellsBuilder_ == null) {
                    ensureCellsIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, cells_);
                    onChanged();
                } else {
                    cellsBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             * <p>
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public Builder clearCells() {
                if (cellsBuilder_ == null) {
                    cells_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    cellsBuilder_.clear();
                }
                return this;
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             * <p>
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public Builder removeCells(int index) {
                if (cellsBuilder_ == null) {
                    ensureCellsIsMutable();
                    cells_.remove(index);
                    onChanged();
                } else {
                    cellsBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             * <p>
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.Builder getCellsBuilder(
                    int index) {
                return getCellsFieldBuilder().getBuilder(index);
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             * <p>
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.CellOrBuilder getCellsOrBuilder(
                    int index) {
                if (cellsBuilder_ == null) {
                    return cells_.get(index);
                } else {
                    return cellsBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             * <p>
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public java.util.List<? extends org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.CellOrBuilder>
            getCellsOrBuilderList() {
                if (cellsBuilder_ != null) {
                    return cellsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(cells_);
                }
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             * <p>
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.Builder addCellsBuilder() {
                return getCellsFieldBuilder().addBuilder(
                        org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.getDefaultInstance());
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             * <p>
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.Builder addCellsBuilder(
                    int index) {
                return getCellsFieldBuilder().addBuilder(
                        index, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.getDefaultInstance());
            }

            /**
             * <pre>
             *    RecoMethod method = 1;
             * </pre>
             * <p>
             * <code>repeated .org.yanzhe.robomaster.recodaemon.net.proto.Cell cells = 2;</code>
             */
            public java.util.List<org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.Builder>
            getCellsBuilderList() {
                return getCellsFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.Builder, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.CellOrBuilder>
            getCellsFieldBuilder() {
                if (cellsBuilder_ == null) {
                    cellsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.Builder, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.CellOrBuilder>(
                            cells_,
                            ((bitField0_ & 0x00000001) == 0x00000001),
                            getParentForChildren(),
                            isClean());
                    cells_ = null;
                }
                return cellsBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:org.yanzhe.robomaster.recodaemon.net.proto.TargetCells)
        }

    }

    /**
     * Protobuf type {@code org.yanzhe.robomaster.recodaemon.net.proto.Cell}
     */
    public static final class Cell extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:org.yanzhe.robomaster.recodaemon.net.proto.Cell)
            CellOrBuilder {
        public static final int SEQ_FIELD_NUMBER = 1;
        public static final int GOAL_FIELD_NUMBER = 2;
        public static final int POS_FIELD_NUMBER = 3;
        public static final int IMG_FIELD_NUMBER = 4;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:org.yanzhe.robomaster.recodaemon.net.proto.Cell)
        private static final org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Cell>
                PARSER = new com.google.protobuf.AbstractParser<Cell>() {
            @java.lang.Override
            public Cell parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Cell(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell();
        }

        private com.google.protobuf.UInt64Value seq_;
        private com.google.protobuf.UInt32Value goal_;
        private com.google.protobuf.Int32Value pos_;
        private org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image img_;
        private byte memoizedIsInitialized = -1;

        // Use Cell.newBuilder() to construct.
        private Cell(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Cell() {
        }

        private Cell(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.UInt64Value.Builder subBuilder = null;
                            if (seq_ != null) {
                                subBuilder = seq_.toBuilder();
                            }
                            seq_ = input.readMessage(com.google.protobuf.UInt64Value.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(seq_);
                                seq_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 18: {
                            com.google.protobuf.UInt32Value.Builder subBuilder = null;
                            if (goal_ != null) {
                                subBuilder = goal_.toBuilder();
                            }
                            goal_ = input.readMessage(com.google.protobuf.UInt32Value.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(goal_);
                                goal_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 26: {
                            com.google.protobuf.Int32Value.Builder subBuilder = null;
                            if (pos_ != null) {
                                subBuilder = pos_.toBuilder();
                            }
                            pos_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(pos_);
                                pos_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 34: {
                            org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.Builder subBuilder = null;
                            if (img_ != null) {
                                subBuilder = img_.toBuilder();
                            }
                            img_ = input.readMessage(org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(img_);
                                img_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Cell_descriptor;
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Cell> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Cell_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.class, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.Builder.class);
        }

        /**
         * <code>.google.protobuf.UInt64Value seq = 1;</code>
         */
        public boolean hasSeq() {
            return seq_ != null;
        }

        /**
         * <code>.google.protobuf.UInt64Value seq = 1;</code>
         */
        public com.google.protobuf.UInt64Value getSeq() {
            return seq_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : seq_;
        }

        /**
         * <code>.google.protobuf.UInt64Value seq = 1;</code>
         */
        public com.google.protobuf.UInt64ValueOrBuilder getSeqOrBuilder() {
            return getSeq();
        }

        /**
         * <code>.google.protobuf.UInt32Value goal = 2;</code>
         */
        public boolean hasGoal() {
            return goal_ != null;
        }

        /**
         * <code>.google.protobuf.UInt32Value goal = 2;</code>
         */
        public com.google.protobuf.UInt32Value getGoal() {
            return goal_ == null ? com.google.protobuf.UInt32Value.getDefaultInstance() : goal_;
        }

        /**
         * <code>.google.protobuf.UInt32Value goal = 2;</code>
         */
        public com.google.protobuf.UInt32ValueOrBuilder getGoalOrBuilder() {
            return getGoal();
        }

        /**
         * <code>.google.protobuf.Int32Value pos = 3;</code>
         */
        public boolean hasPos() {
            return pos_ != null;
        }

        /**
         * <code>.google.protobuf.Int32Value pos = 3;</code>
         */
        public com.google.protobuf.Int32Value getPos() {
            return pos_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : pos_;
        }

        /**
         * <code>.google.protobuf.Int32Value pos = 3;</code>
         */
        public com.google.protobuf.Int32ValueOrBuilder getPosOrBuilder() {
            return getPos();
        }

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
         */
        public boolean hasImg() {
            return img_ != null;
        }

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
         */
        public org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image getImg() {
            return img_ == null ? org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.getDefaultInstance() : img_;
        }

        /**
         * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
         */
        public org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.ImageOrBuilder getImgOrBuilder() {
            return getImg();
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (seq_ != null) {
                output.writeMessage(1, getSeq());
            }
            if (goal_ != null) {
                output.writeMessage(2, getGoal());
            }
            if (pos_ != null) {
                output.writeMessage(3, getPos());
            }
            if (img_ != null) {
                output.writeMessage(4, getImg());
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (seq_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getSeq());
            }
            if (goal_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getGoal());
            }
            if (pos_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, getPos());
            }
            if (img_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, getImg());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell)) {
                return super.equals(obj);
            }
            org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell other = (org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell) obj;

            boolean result = true;
            result = result && (hasSeq() == other.hasSeq());
            if (hasSeq()) {
                result = result && getSeq()
                        .equals(other.getSeq());
            }
            result = result && (hasGoal() == other.hasGoal());
            if (hasGoal()) {
                result = result && getGoal()
                        .equals(other.getGoal());
            }
            result = result && (hasPos() == other.hasPos());
            if (hasPos()) {
                result = result && getPos()
                        .equals(other.getPos());
            }
            result = result && (hasImg() == other.hasImg());
            if (hasImg()) {
                result = result && getImg()
                        .equals(other.getImg());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasSeq()) {
                hash = (37 * hash) + SEQ_FIELD_NUMBER;
                hash = (53 * hash) + getSeq().hashCode();
            }
            if (hasGoal()) {
                hash = (37 * hash) + GOAL_FIELD_NUMBER;
                hash = (53 * hash) + getGoal().hashCode();
            }
            if (hasPos()) {
                hash = (37 * hash) + POS_FIELD_NUMBER;
                hash = (53 * hash) + getPos().hashCode();
            }
            if (hasImg()) {
                hash = (37 * hash) + IMG_FIELD_NUMBER;
                hash = (53 * hash) + getImg().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Cell> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code org.yanzhe.robomaster.recodaemon.net.proto.Cell}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:org.yanzhe.robomaster.recodaemon.net.proto.Cell)
                org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.CellOrBuilder {
            private com.google.protobuf.UInt64Value seq_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> seqBuilder_;
            private com.google.protobuf.UInt32Value goal_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder> goalBuilder_;
            private com.google.protobuf.Int32Value pos_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> posBuilder_;
            private org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image img_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image, org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.Builder, org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.ImageOrBuilder> imgBuilder_;

            // Construct using org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Cell_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Cell_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.class, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (seqBuilder_ == null) {
                    seq_ = null;
                } else {
                    seq_ = null;
                    seqBuilder_ = null;
                }
                if (goalBuilder_ == null) {
                    goal_ = null;
                } else {
                    goal_ = null;
                    goalBuilder_ = null;
                }
                if (posBuilder_ == null) {
                    pos_ = null;
                } else {
                    pos_ = null;
                    posBuilder_ = null;
                }
                if (imgBuilder_ == null) {
                    img_ = null;
                } else {
                    img_ = null;
                    imgBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.internal_static_org_yanzhe_robomaster_recodaemon_net_proto_Cell_descriptor;
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell getDefaultInstanceForType() {
                return org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.getDefaultInstance();
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell build() {
                org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell buildPartial() {
                org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell result = new org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell(this);
                if (seqBuilder_ == null) {
                    result.seq_ = seq_;
                } else {
                    result.seq_ = seqBuilder_.build();
                }
                if (goalBuilder_ == null) {
                    result.goal_ = goal_;
                } else {
                    result.goal_ = goalBuilder_.build();
                }
                if (posBuilder_ == null) {
                    result.pos_ = pos_;
                } else {
                    result.pos_ = posBuilder_.build();
                }
                if (imgBuilder_ == null) {
                    result.img_ = img_;
                } else {
                    result.img_ = imgBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell) {
                    return mergeFrom((org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell other) {
                if (other == org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell.getDefaultInstance())
                    return this;
                if (other.hasSeq()) {
                    mergeSeq(other.getSeq());
                }
                if (other.hasGoal()) {
                    mergeGoal(other.getGoal());
                }
                if (other.hasPos()) {
                    mergePos(other.getPos());
                }
                if (other.hasImg()) {
                    mergeImg(other.getImg());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.Cell) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>.google.protobuf.UInt64Value seq = 1;</code>
             */
            public boolean hasSeq() {
                return seqBuilder_ != null || seq_ != null;
            }

            /**
             * <code>.google.protobuf.UInt64Value seq = 1;</code>
             */
            public com.google.protobuf.UInt64Value getSeq() {
                if (seqBuilder_ == null) {
                    return seq_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : seq_;
                } else {
                    return seqBuilder_.getMessage();
                }
            }

            /**
             * <code>.google.protobuf.UInt64Value seq = 1;</code>
             */
            public Builder setSeq(
                    com.google.protobuf.UInt64Value.Builder builderForValue) {
                if (seqBuilder_ == null) {
                    seq_ = builderForValue.build();
                    onChanged();
                } else {
                    seqBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.google.protobuf.UInt64Value seq = 1;</code>
             */
            public Builder setSeq(com.google.protobuf.UInt64Value value) {
                if (seqBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    seq_ = value;
                    onChanged();
                } else {
                    seqBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.UInt64Value seq = 1;</code>
             */
            public Builder mergeSeq(com.google.protobuf.UInt64Value value) {
                if (seqBuilder_ == null) {
                    if (seq_ != null) {
                        seq_ =
                                com.google.protobuf.UInt64Value.newBuilder(seq_).mergeFrom(value).buildPartial();
                    } else {
                        seq_ = value;
                    }
                    onChanged();
                } else {
                    seqBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.UInt64Value seq = 1;</code>
             */
            public Builder clearSeq() {
                if (seqBuilder_ == null) {
                    seq_ = null;
                    onChanged();
                } else {
                    seq_ = null;
                    seqBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.google.protobuf.UInt64Value seq = 1;</code>
             */
            public com.google.protobuf.UInt64Value.Builder getSeqBuilder() {

                onChanged();
                return getSeqFieldBuilder().getBuilder();
            }

            /**
             * <code>.google.protobuf.UInt64Value seq = 1;</code>
             */
            public com.google.protobuf.UInt64ValueOrBuilder getSeqOrBuilder() {
                if (seqBuilder_ != null) {
                    return seqBuilder_.getMessageOrBuilder();
                } else {
                    return seq_ == null ?
                            com.google.protobuf.UInt64Value.getDefaultInstance() : seq_;
                }
            }

            /**
             * <code>.google.protobuf.UInt64Value seq = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder>
            getSeqFieldBuilder() {
                if (seqBuilder_ == null) {
                    seqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder>(
                            getSeq(),
                            getParentForChildren(),
                            isClean());
                    seq_ = null;
                }
                return seqBuilder_;
            }

            /**
             * <code>.google.protobuf.UInt32Value goal = 2;</code>
             */
            public boolean hasGoal() {
                return goalBuilder_ != null || goal_ != null;
            }

            /**
             * <code>.google.protobuf.UInt32Value goal = 2;</code>
             */
            public com.google.protobuf.UInt32Value getGoal() {
                if (goalBuilder_ == null) {
                    return goal_ == null ? com.google.protobuf.UInt32Value.getDefaultInstance() : goal_;
                } else {
                    return goalBuilder_.getMessage();
                }
            }

            /**
             * <code>.google.protobuf.UInt32Value goal = 2;</code>
             */
            public Builder setGoal(
                    com.google.protobuf.UInt32Value.Builder builderForValue) {
                if (goalBuilder_ == null) {
                    goal_ = builderForValue.build();
                    onChanged();
                } else {
                    goalBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.google.protobuf.UInt32Value goal = 2;</code>
             */
            public Builder setGoal(com.google.protobuf.UInt32Value value) {
                if (goalBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    goal_ = value;
                    onChanged();
                } else {
                    goalBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.UInt32Value goal = 2;</code>
             */
            public Builder mergeGoal(com.google.protobuf.UInt32Value value) {
                if (goalBuilder_ == null) {
                    if (goal_ != null) {
                        goal_ =
                                com.google.protobuf.UInt32Value.newBuilder(goal_).mergeFrom(value).buildPartial();
                    } else {
                        goal_ = value;
                    }
                    onChanged();
                } else {
                    goalBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.UInt32Value goal = 2;</code>
             */
            public Builder clearGoal() {
                if (goalBuilder_ == null) {
                    goal_ = null;
                    onChanged();
                } else {
                    goal_ = null;
                    goalBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.google.protobuf.UInt32Value goal = 2;</code>
             */
            public com.google.protobuf.UInt32Value.Builder getGoalBuilder() {

                onChanged();
                return getGoalFieldBuilder().getBuilder();
            }

            /**
             * <code>.google.protobuf.UInt32Value goal = 2;</code>
             */
            public com.google.protobuf.UInt32ValueOrBuilder getGoalOrBuilder() {
                if (goalBuilder_ != null) {
                    return goalBuilder_.getMessageOrBuilder();
                } else {
                    return goal_ == null ?
                            com.google.protobuf.UInt32Value.getDefaultInstance() : goal_;
                }
            }

            /**
             * <code>.google.protobuf.UInt32Value goal = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder>
            getGoalFieldBuilder() {
                if (goalBuilder_ == null) {
                    goalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder>(
                            getGoal(),
                            getParentForChildren(),
                            isClean());
                    goal_ = null;
                }
                return goalBuilder_;
            }

            /**
             * <code>.google.protobuf.Int32Value pos = 3;</code>
             */
            public boolean hasPos() {
                return posBuilder_ != null || pos_ != null;
            }

            /**
             * <code>.google.protobuf.Int32Value pos = 3;</code>
             */
            public com.google.protobuf.Int32Value getPos() {
                if (posBuilder_ == null) {
                    return pos_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : pos_;
                } else {
                    return posBuilder_.getMessage();
                }
            }

            /**
             * <code>.google.protobuf.Int32Value pos = 3;</code>
             */
            public Builder setPos(
                    com.google.protobuf.Int32Value.Builder builderForValue) {
                if (posBuilder_ == null) {
                    pos_ = builderForValue.build();
                    onChanged();
                } else {
                    posBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value pos = 3;</code>
             */
            public Builder setPos(com.google.protobuf.Int32Value value) {
                if (posBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    pos_ = value;
                    onChanged();
                } else {
                    posBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value pos = 3;</code>
             */
            public Builder mergePos(com.google.protobuf.Int32Value value) {
                if (posBuilder_ == null) {
                    if (pos_ != null) {
                        pos_ =
                                com.google.protobuf.Int32Value.newBuilder(pos_).mergeFrom(value).buildPartial();
                    } else {
                        pos_ = value;
                    }
                    onChanged();
                } else {
                    posBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value pos = 3;</code>
             */
            public Builder clearPos() {
                if (posBuilder_ == null) {
                    pos_ = null;
                    onChanged();
                } else {
                    pos_ = null;
                    posBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Int32Value pos = 3;</code>
             */
            public com.google.protobuf.Int32Value.Builder getPosBuilder() {

                onChanged();
                return getPosFieldBuilder().getBuilder();
            }

            /**
             * <code>.google.protobuf.Int32Value pos = 3;</code>
             */
            public com.google.protobuf.Int32ValueOrBuilder getPosOrBuilder() {
                if (posBuilder_ != null) {
                    return posBuilder_.getMessageOrBuilder();
                } else {
                    return pos_ == null ?
                            com.google.protobuf.Int32Value.getDefaultInstance() : pos_;
                }
            }

            /**
             * <code>.google.protobuf.Int32Value pos = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>
            getPosFieldBuilder() {
                if (posBuilder_ == null) {
                    posBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                            getPos(),
                            getParentForChildren(),
                            isClean());
                    pos_ = null;
                }
                return posBuilder_;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
             */
            public boolean hasImg() {
                return imgBuilder_ != null || img_ != null;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
             */
            public org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image getImg() {
                if (imgBuilder_ == null) {
                    return img_ == null ? org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.getDefaultInstance() : img_;
                } else {
                    return imgBuilder_.getMessage();
                }
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
             */
            public Builder setImg(
                    org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.Builder builderForValue) {
                if (imgBuilder_ == null) {
                    img_ = builderForValue.build();
                    onChanged();
                } else {
                    imgBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
             */
            public Builder setImg(org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image value) {
                if (imgBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    img_ = value;
                    onChanged();
                } else {
                    imgBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
             */
            public Builder mergeImg(org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image value) {
                if (imgBuilder_ == null) {
                    if (img_ != null) {
                        img_ =
                                org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.newBuilder(img_).mergeFrom(value).buildPartial();
                    } else {
                        img_ = value;
                    }
                    onChanged();
                } else {
                    imgBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
             */
            public Builder clearImg() {
                if (imgBuilder_ == null) {
                    img_ = null;
                    onChanged();
                } else {
                    img_ = null;
                    imgBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
             */
            public org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.Builder getImgBuilder() {

                onChanged();
                return getImgFieldBuilder().getBuilder();
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
             */
            public org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.ImageOrBuilder getImgOrBuilder() {
                if (imgBuilder_ != null) {
                    return imgBuilder_.getMessageOrBuilder();
                } else {
                    return img_ == null ?
                            org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.getDefaultInstance() : img_;
                }
            }

            /**
             * <code>.org.yanzhe.robomaster.recodaemon.net.proto.Image img = 4;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image, org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.Builder, org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.ImageOrBuilder>
            getImgFieldBuilder() {
                if (imgBuilder_ == null) {
                    imgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image, org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.Image.Builder, org.yanzhe.robomaster.recodaemon.net.proto.ImageProto.ImageOrBuilder>(
                  getImg(),
                  getParentForChildren(),
                  isClean());
          img_ = null;
        }
        return imgBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.yanzhe.robomaster.recodaemon.net.proto.Cell)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
