// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TargetCells.proto

package org.yanzhe.robomaster.recodaemon.net.proto;

public final class TargetCellsProto {
  private TargetCellsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TargetCellsOrBuilder extends
          // @@protoc_insertion_point(interface_extends:google.protobuf.TargetCells)
          com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
     */
    java.util.List<org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell> 
        getCellsList();
    /**
     * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
     */
    org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell getCells(int index);
    /**
     * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
     */
    int getCellsCount();
  }
  /**
   * Protobuf type {@code google.protobuf.TargetCells}
   */
  public  static final class TargetCells extends
          com.google.protobuf.GeneratedMessageLite<
                  TargetCells, TargetCells.Builder> implements
          // @@protoc_insertion_point(message_implements:google.protobuf.TargetCells)
      TargetCellsOrBuilder {
      // @@protoc_insertion_point(class_scope:google.protobuf.TargetCells)
      private static final org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells DEFAULT_INSTANCE;
      private static volatile com.google.protobuf.Parser<TargetCells> PARSER;

      static {
          DEFAULT_INSTANCE = new TargetCells();
          DEFAULT_INSTANCE.makeImmutable();
    }

      public static final int CELLS_FIELD_NUMBER = 1;

      private com.google.protobuf.Internal.ProtobufList<org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell> cells_;
    private TargetCells() {
        cells_ = emptyProtobufList();
    }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
              java.nio.ByteBuffer data)
              throws com.google.protobuf.InvalidProtocolBufferException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
                  DEFAULT_INSTANCE, data);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
              java.nio.ByteBuffer data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
                  DEFAULT_INSTANCE, data, extensionRegistry);
    }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
              com.google.protobuf.ByteString data)
              throws com.google.protobuf.InvalidProtocolBufferException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
                  DEFAULT_INSTANCE, data);
    }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
              com.google.protobuf.ByteString data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
                  DEFAULT_INSTANCE, data, extensionRegistry);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(byte[] data)
              throws com.google.protobuf.InvalidProtocolBufferException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
                  DEFAULT_INSTANCE, data);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
              byte[] data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
                  DEFAULT_INSTANCE, data, extensionRegistry);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(java.io.InputStream input)
              throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
                  DEFAULT_INSTANCE, input);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
                  DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseDelimitedFrom(java.io.InputStream input)
              throws java.io.IOException {
          return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseDelimitedFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
          return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
              com.google.protobuf.CodedInputStream input)
              throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
                  DEFAULT_INSTANCE, input);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
                  DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
          return (Builder) DEFAULT_INSTANCE.createBuilder();
      }

      public static Builder newBuilder(org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells prototype) {
          return DEFAULT_INSTANCE.createBuilder(prototype);
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
              throws java.io.IOException {
          for (int i = 0; i < cells_.size(); i++) {
              output.writeMessage(1, cells_.get(i));
          }
          unknownFields.writeTo(output);
      }

      public static com.google.protobuf.Parser<TargetCells> parser() {
          return DEFAULT_INSTANCE.getParserForType();
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public java.util.List<org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell> getCellsList() {
          return cells_;
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public java.util.List<? extends org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.CellOrBuilder>
      getCellsOrBuilderList() {
          return cells_;
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public int getCellsCount() {
          return cells_.size();
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell getCells(int index) {
          return cells_.get(index);
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.CellOrBuilder getCellsOrBuilder(
              int index) {
          return cells_.get(index);
      }

      private void ensureCellsIsMutable() {
          if (!cells_.isModifiable()) {
              cells_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(cells_);
          }
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      private void setCells(
              int index, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell value) {
          if (value == null) {
              throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.set(index, value);
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      private void setCells(
              int index, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell.Builder builderForValue) {
          ensureCellsIsMutable();
          cells_.set(index, builderForValue.build());
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      private void addCells(org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell value) {
          if (value == null) {
              throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.add(value);
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      private void addCells(
              int index, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell value) {
          if (value == null) {
              throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.add(index, value);
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      private void addCells(
              org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell.Builder builderForValue) {
          ensureCellsIsMutable();
          cells_.add(builderForValue.build());
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      private void addCells(
              int index, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell.Builder builderForValue) {
          ensureCellsIsMutable();
          cells_.add(index, builderForValue.build());
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      private void addAllCells(
              java.lang.Iterable<? extends org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell> values) {
          ensureCellsIsMutable();
          com.google.protobuf.AbstractMessageLite.addAll(
                  values, cells_);
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      private void clearCells() {
          cells_ = emptyProtobufList();
      }

      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      private void removeCells(int index) {
          ensureCellsIsMutable();
          cells_.remove(index);
      }

      public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;

          size = 0;
          for (int i = 0; i < cells_.size(); i++) {
              size += com.google.protobuf.CodedOutputStream
                      .computeMessageSize(1, cells_.get(i));
          }
          size += unknownFields.getSerializedSize();
          memoizedSerializedSize = size;
          return size;
      }

      @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
      protected final java.lang.Object dynamicMethod(
              com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
              java.lang.Object arg0, java.lang.Object arg1) {
          switch (method) {
              case NEW_MUTABLE_INSTANCE: {
                  return new org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells();
              }
              case IS_INITIALIZED: {
                  return DEFAULT_INSTANCE;
              }
              case MAKE_IMMUTABLE: {
                  cells_.makeImmutable();
                  return null;
              }
              case NEW_BUILDER: {
                  return new Builder();
              }
              case VISIT: {
                  Visitor visitor = (Visitor) arg0;
                  org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells other = (org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells) arg1;
                  cells_ = visitor.visitList(cells_, other.cells_);
                  if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                          .INSTANCE) {
                  }
                  return this;
              }
              case MERGE_FROM_STREAM: {
                  com.google.protobuf.CodedInputStream input =
                          (com.google.protobuf.CodedInputStream) arg0;
                  com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                          (com.google.protobuf.ExtensionRegistryLite) arg1;
                  if (extensionRegistry == null) {
                      throw new java.lang.NullPointerException();
                  }
                  try {
                      boolean done = false;
                      while (!done) {
                          int tag = input.readTag();
                          switch (tag) {
                              case 0:
                                  done = true;
                                  break;
                              case 10: {
                                  if (!cells_.isModifiable()) {
                                      cells_ =
                                              com.google.protobuf.GeneratedMessageLite.mutableCopy(cells_);
                                  }
                                  cells_.add(
                                          input.readMessage(org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell.parser(), extensionRegistry));
                                  break;
                              }
                              default: {
                                  if (!parseUnknownField(tag, input)) {
                                      done = true;
                                  }
                                  break;
                              }
                          }
                      }
                  } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                      throw new RuntimeException(e.setUnfinishedMessage(this));
                  } catch (java.io.IOException e) {
                      throw new RuntimeException(
                              new com.google.protobuf.InvalidProtocolBufferException(
                                      e.getMessage()).setUnfinishedMessage(this));
                  } finally {
                  }
              }
              // fall through
              case GET_DEFAULT_INSTANCE: {
                  return DEFAULT_INSTANCE;
              }
              case GET_PARSER: {
                  if (PARSER == null) {
                      synchronized (org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.class) {
                          if (PARSER == null) {
                              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                          }
                      }
                  }
                  return PARSER;
              }
              case GET_MEMOIZED_IS_INITIALIZED: {
                  return (byte) 1;
              }
              case SET_MEMOIZED_IS_INITIALIZED: {
                  return null;
              }
          }
          throw new UnsupportedOperationException();
      }

      public interface CellOrBuilder extends
              // @@protoc_insertion_point(interface_extends:google.protobuf.TargetCells.Cell)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>.google.protobuf.UInt64Value seq = 1;</code>
       */
      boolean hasSeq();
      /**
       * <code>.google.protobuf.UInt64Value seq = 1;</code>
       */
      com.google.protobuf.UInt64Value getSeq();

      /**
       * <code>.google.protobuf.UInt32Value goal = 2;</code>
       */
      boolean hasGoal();
      /**
       * <code>.google.protobuf.UInt32Value goal = 2;</code>
       */
      com.google.protobuf.UInt32Value getGoal();

      /**
       * <code>.google.protobuf.Int32Value pos = 3;</code>
       */
      boolean hasPos();
      /**
       * <code>.google.protobuf.Int32Value pos = 3;</code>
       */
      com.google.protobuf.Int32Value getPos();

          /**
           * <code>bytes img = 4;</code>
           */
          com.google.protobuf.ByteString getImg();
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells getDefaultInstance() {
          return DEFAULT_INSTANCE;
      }

      /**
       * Protobuf type {@code google.protobuf.TargetCells.Cell}
       */
      public static final class Cell extends
              com.google.protobuf.GeneratedMessageLite<
                      Cell, Cell.Builder> implements
        // @@protoc_insertion_point(message_implements:google.protobuf.TargetCells.Cell)
        CellOrBuilder {
      private Cell() {
        img_ = com.google.protobuf.ByteString.EMPTY;
      }
      public static final int SEQ_FIELD_NUMBER = 1;
      private com.google.protobuf.UInt64Value seq_;
      /**
       * <code>.google.protobuf.UInt64Value seq = 1;</code>
       */
      public boolean hasSeq() {
        return seq_ != null;
      }
      /**
       * <code>.google.protobuf.UInt64Value seq = 1;</code>
       */
      public com.google.protobuf.UInt64Value getSeq() {
          return seq_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : seq_;
      }

          // @@protoc_insertion_point(class_scope:google.protobuf.TargetCells.Cell)
          private static final org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell DEFAULT_INSTANCE;
          private static volatile com.google.protobuf.Parser<Cell> PARSER;

          static {
              DEFAULT_INSTANCE = new Cell();
              DEFAULT_INSTANCE.makeImmutable();
          }

          public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell parseFrom(
                  java.nio.ByteBuffer data)
                  throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }

      public static final int GOAL_FIELD_NUMBER = 2;
      private com.google.protobuf.UInt32Value goal_;
      /**
       * <code>.google.protobuf.UInt32Value goal = 2;</code>
       */
      public boolean hasGoal() {
        return goal_ != null;
      }
      /**
       * <code>.google.protobuf.UInt32Value goal = 2;</code>
       */
      public com.google.protobuf.UInt32Value getGoal() {
        return goal_ == null ? com.google.protobuf.UInt32Value.getDefaultInstance() : goal_;
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell parseFrom(
              java.nio.ByteBuffer data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell parseFrom(
              com.google.protobuf.ByteString data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell parseFrom(
              com.google.protobuf.ByteString data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell parseFrom(byte[] data)
              throws com.google.protobuf.InvalidProtocolBufferException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
                  DEFAULT_INSTANCE, data);
      }

          public static final int POS_FIELD_NUMBER = 3;
          private com.google.protobuf.Int32Value pos_;

          /**
           * <code>.google.protobuf.Int32Value pos = 3;</code>
           */
          public boolean hasPos() {
              return pos_ != null;
          }

          /**
           * <code>.google.protobuf.Int32Value pos = 3;</code>
           */
          public com.google.protobuf.Int32Value getPos() {
              return pos_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : pos_;
          }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell parseFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell parseDelimitedFrom(java.io.InputStream input)
              throws java.io.IOException {
          return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }

          public static final int IMG_FIELD_NUMBER = 4;
          private com.google.protobuf.ByteString img_;
      /**
       * <code>bytes img = 4;</code>
       */
      public com.google.protobuf.ByteString getImg() {
        return img_;
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell parseDelimitedFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell parseFrom(
              com.google.protobuf.CodedInputStream input)
              throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageLite.parseFrom(
                  DEFAULT_INSTANCE, input);
      }

          public void writeTo(com.google.protobuf.CodedOutputStream output)
                  throws java.io.IOException {
              if (seq_ != null) {
                  output.writeMessage(1, getSeq());
              }
              if (goal_ != null) {
                  output.writeMessage(2, getGoal());
              }
              if (pos_ != null) {
                  output.writeMessage(3, getPos());
              }
              if (!img_.isEmpty()) {
                  output.writeBytes(4, img_);
              }
              unknownFields.writeTo(output);
          }

      public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }

          public static Builder newBuilder(org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell prototype) {
              return DEFAULT_INSTANCE.createBuilder(prototype);
          }

          public static com.google.protobuf.Parser<Cell> parser() {
              return DEFAULT_INSTANCE.getParserForType();
          }

          /**
           * <code>.google.protobuf.UInt64Value seq = 1;</code>
           */
          private void setSeq(com.google.protobuf.UInt64Value value) {
              if (value == null) {
                  throw new NullPointerException();
              }
              seq_ = value;

          }

          /**
           * <code>.google.protobuf.UInt64Value seq = 1;</code>
           */
          private void setSeq(
                  com.google.protobuf.UInt64Value.Builder builderForValue) {
              seq_ = builderForValue.build();

          }

          /**
           * <code>.google.protobuf.UInt64Value seq = 1;</code>
           */
          private void mergeSeq(com.google.protobuf.UInt64Value value) {
              if (seq_ != null &&
                      seq_ != com.google.protobuf.UInt64Value.getDefaultInstance()) {
                  seq_ =
                          com.google.protobuf.UInt64Value.newBuilder(seq_).mergeFrom(value).buildPartial();
              } else {
                  seq_ = value;
              }

          }

          /**
           * <code>.google.protobuf.UInt64Value seq = 1;</code>
           */
          private void clearSeq() {
              seq_ = null;

          }

          /**
           * <code>.google.protobuf.UInt32Value goal = 2;</code>
           */
          private void setGoal(com.google.protobuf.UInt32Value value) {
              if (value == null) {
                  throw new NullPointerException();
              }
              goal_ = value;

          }

          /**
           * <code>.google.protobuf.UInt32Value goal = 2;</code>
           */
          private void setGoal(
                  com.google.protobuf.UInt32Value.Builder builderForValue) {
              goal_ = builderForValue.build();

          }

          /**
           * <code>.google.protobuf.UInt32Value goal = 2;</code>
           */
          private void mergeGoal(com.google.protobuf.UInt32Value value) {
              if (goal_ != null &&
                      goal_ != com.google.protobuf.UInt32Value.getDefaultInstance()) {
                  goal_ =
                          com.google.protobuf.UInt32Value.newBuilder(goal_).mergeFrom(value).buildPartial();
              } else {
                  goal_ = value;
              }

          }

          /**
           * <code>.google.protobuf.UInt32Value goal = 2;</code>
           */
          private void clearGoal() {
              goal_ = null;

          }

          /**
           * <code>.google.protobuf.Int32Value pos = 3;</code>
           */
          private void setPos(com.google.protobuf.Int32Value value) {
              if (value == null) {
                  throw new NullPointerException();
              }
              pos_ = value;

          }

          /**
           * <code>.google.protobuf.Int32Value pos = 3;</code>
           */
          private void setPos(
                  com.google.protobuf.Int32Value.Builder builderForValue) {
              pos_ = builderForValue.build();

          }

          /**
           * <code>.google.protobuf.Int32Value pos = 3;</code>
           */
          private void mergePos(com.google.protobuf.Int32Value value) {
              if (pos_ != null &&
                      pos_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
                  pos_ =
                          com.google.protobuf.Int32Value.newBuilder(pos_).mergeFrom(value).buildPartial();
              } else {
                  pos_ = value;
              }

          }

          /**
           * <code>.google.protobuf.Int32Value pos = 3;</code>
           */
          private void clearPos() {
              pos_ = null;

          }

          /**
           * <code>bytes img = 4;</code>
           */
          private void setImg(com.google.protobuf.ByteString value) {
              if (value == null) {
                  throw new NullPointerException();
              }

              img_ = value;
          }

          /**
           * <code>bytes img = 4;</code>
           */
          private void clearImg() {

              img_ = getDefaultInstance().getImg();
          }

          public int getSerializedSize() {
              int size = memoizedSerializedSize;
              if (size != -1) return size;

              size = 0;
              if (seq_ != null) {
                  size += com.google.protobuf.CodedOutputStream
                          .computeMessageSize(1, getSeq());
              }
              if (goal_ != null) {
                  size += com.google.protobuf.CodedOutputStream
                          .computeMessageSize(2, getGoal());
              }
              if (pos_ != null) {
                  size += com.google.protobuf.CodedOutputStream
                          .computeMessageSize(3, getPos());
              }
              if (!img_.isEmpty()) {
                  size += com.google.protobuf.CodedOutputStream
                          .computeBytesSize(4, img_);
              }
              size += unknownFields.getSerializedSize();
              memoizedSerializedSize = size;
              return size;
          }

          public static org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell getDefaultInstance() {
              return DEFAULT_INSTANCE;
          }

          @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
          protected final java.lang.Object dynamicMethod(
                  com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                  java.lang.Object arg0, java.lang.Object arg1) {
              switch (method) {
                  case NEW_MUTABLE_INSTANCE: {
                      return new org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell();
                  }
                  case IS_INITIALIZED: {
                      return DEFAULT_INSTANCE;
                  }
                  case MAKE_IMMUTABLE: {
                      return null;
                  }
                  case NEW_BUILDER: {
                      return new Builder();
                  }
                  case VISIT: {
                      Visitor visitor = (Visitor) arg0;
                      org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell other = (org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell) arg1;
                      seq_ = visitor.visitMessage(seq_, other.seq_);
                      goal_ = visitor.visitMessage(goal_, other.goal_);
                      pos_ = visitor.visitMessage(pos_, other.pos_);
                      img_ = visitor.visitByteString(img_ != com.google.protobuf.ByteString.EMPTY, img_,
                              other.img_ != com.google.protobuf.ByteString.EMPTY, other.img_);
                      if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                              .INSTANCE) {
                      }
                      return this;
                  }
                  case MERGE_FROM_STREAM: {
                      com.google.protobuf.CodedInputStream input =
                              (com.google.protobuf.CodedInputStream) arg0;
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                              (com.google.protobuf.ExtensionRegistryLite) arg1;
                      if (extensionRegistry == null) {
                          throw new java.lang.NullPointerException();
                      }
                      try {
                          boolean done = false;
                          while (!done) {
                              int tag = input.readTag();
                              switch (tag) {
                                  case 0:
                                      done = true;
                                      break;
                                  case 10: {
                                      com.google.protobuf.UInt64Value.Builder subBuilder = null;
                                      if (seq_ != null) {
                                          subBuilder = seq_.toBuilder();
                                      }
                                      seq_ = input.readMessage(com.google.protobuf.UInt64Value.parser(), extensionRegistry);
                                      if (subBuilder != null) {
                                          subBuilder.mergeFrom(seq_);
                                          seq_ = subBuilder.buildPartial();
                                      }

                                      break;
                                  }
                                  case 18: {
                                      com.google.protobuf.UInt32Value.Builder subBuilder = null;
                                      if (goal_ != null) {
                                          subBuilder = goal_.toBuilder();
                                      }
                                      goal_ = input.readMessage(com.google.protobuf.UInt32Value.parser(), extensionRegistry);
                                      if (subBuilder != null) {
                                          subBuilder.mergeFrom(goal_);
                                          goal_ = subBuilder.buildPartial();
                                      }

                                      break;
                                  }
                                  case 26: {
                                      com.google.protobuf.Int32Value.Builder subBuilder = null;
                                      if (pos_ != null) {
                                          subBuilder = pos_.toBuilder();
                                      }
                                      pos_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
                                      if (subBuilder != null) {
                                          subBuilder.mergeFrom(pos_);
                                          pos_ = subBuilder.buildPartial();
                                      }

                                      break;
                                  }
                                  case 34: {

                                      img_ = input.readBytes();
                                      break;
                                  }
                                  default: {
                                      if (!parseUnknownField(tag, input)) {
                                          done = true;
                                      }
                                      break;
                                  }
                              }
                          }
                      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                          throw new RuntimeException(e.setUnfinishedMessage(this));
                      } catch (java.io.IOException e) {
                          throw new RuntimeException(
                                  new com.google.protobuf.InvalidProtocolBufferException(
                                          e.getMessage()).setUnfinishedMessage(this));
                      } finally {
                      }
                  }
                  // fall through
                  case GET_DEFAULT_INSTANCE: {
                      return DEFAULT_INSTANCE;
                  }
                  case GET_PARSER: {
                      if (PARSER == null) {
                          synchronized (org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell.class) {
                              if (PARSER == null) {
                                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                              }
                          }
                      }
                      return PARSER;
                  }
                  case GET_MEMOIZED_IS_INITIALIZED: {
                      return (byte) 1;
                  }
                  case SET_MEMOIZED_IS_INITIALIZED: {
                      return null;
                  }
              }
              throw new UnsupportedOperationException();
          }

          /**
           * Protobuf type {@code google.protobuf.TargetCells.Cell}
           */
          public static final class Builder extends
                  com.google.protobuf.GeneratedMessageLite.Builder<
                          org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell, Builder> implements
                  // @@protoc_insertion_point(builder_implements:google.protobuf.TargetCells.Cell)
          org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.CellOrBuilder {
        // Construct using org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>.google.protobuf.UInt64Value seq = 1;</code>
         */
        public boolean hasSeq() {
          return instance.hasSeq();
        }

              /**
               * <code>.google.protobuf.UInt64Value seq = 1;</code>
               */
              public com.google.protobuf.UInt64Value getSeq() {
                  return instance.getSeq();
        }

        /**
         * <code>.google.protobuf.UInt64Value seq = 1;</code>
         */
        public Builder setSeq(
                com.google.protobuf.UInt64Value.Builder builderForValue) {
            copyOnWrite();
            instance.setSeq(builderForValue);
          return this;
        }

        /**
         * <code>.google.protobuf.UInt64Value seq = 1;</code>
         */
        public Builder setSeq(com.google.protobuf.UInt64Value value) {
          copyOnWrite();
          instance.setSeq(value);
          return this;
          }

        /**
         * <code>.google.protobuf.UInt64Value seq = 1;</code>
         */
        public Builder mergeSeq(com.google.protobuf.UInt64Value value) {
          copyOnWrite();
          instance.mergeSeq(value);
          return this;
        }
        /**
         * <code>.google.protobuf.UInt64Value seq = 1;</code>
         */
        public Builder clearSeq() {  copyOnWrite();
          instance.clearSeq();
          return this;
        }

              /**
               * <code>.google.protobuf.UInt32Value goal = 2;</code>
         */
        public boolean hasGoal() {
          return instance.hasGoal();
        }
        /**
         * <code>.google.protobuf.UInt32Value goal = 2;</code>
         */
        public com.google.protobuf.UInt32Value getGoal() {
          return instance.getGoal();
        }

        /**
         * <code>.google.protobuf.UInt32Value goal = 2;</code>
         */
        public Builder setGoal(
                com.google.protobuf.UInt32Value.Builder builderForValue) {
            copyOnWrite();
            instance.setGoal(builderForValue);
          return this;
        }

        /**
         * <code>.google.protobuf.UInt32Value goal = 2;</code>
         */
        public Builder setGoal(com.google.protobuf.UInt32Value value) {
            copyOnWrite();
          instance.setGoal(value);
          return this;
          }

        /**
         * <code>.google.protobuf.UInt32Value goal = 2;</code>
         */
        public Builder mergeGoal(com.google.protobuf.UInt32Value value) {
          copyOnWrite();
          instance.mergeGoal(value);
          return this;
        }
        /**
         * <code>.google.protobuf.UInt32Value goal = 2;</code>
         */
        public Builder clearGoal() {  copyOnWrite();
          instance.clearGoal();
          return this;
        }

              /**
               * <code>.google.protobuf.Int32Value pos = 3;</code>
         */
        public boolean hasPos() {
            return instance.hasPos();
        }

              /**
               * <code>.google.protobuf.Int32Value pos = 3;</code>
               */
              public com.google.protobuf.Int32Value getPos() {
          return instance.getPos();
        }

        /**
         * <code>.google.protobuf.Int32Value pos = 3;</code>
         */
        public Builder setPos(
                com.google.protobuf.Int32Value.Builder builderForValue) {
            copyOnWrite();
          instance.setPos(builderForValue);
          return this;
        }

        /**
         * <code>.google.protobuf.Int32Value pos = 3;</code>
         */
        public Builder setPos(com.google.protobuf.Int32Value value) {
          copyOnWrite();
          instance.setPos(value);
          return this;
          }

              /**
               * <code>.google.protobuf.Int32Value pos = 3;</code>
               */
              public Builder mergePos(com.google.protobuf.Int32Value value) {
          copyOnWrite();
          instance.mergePos(value);
                  return this;
              }

              /**
         * <code>.google.protobuf.Int32Value pos = 3;</code>
         */
        public Builder clearPos() {  copyOnWrite();
          instance.clearPos();
            return this;
        }

              /**
         * <code>bytes img = 4;</code>
         */
        public com.google.protobuf.ByteString getImg() {
          return instance.getImg();
        }

              /**
               * <code>bytes img = 4;</code>
         */
              public Builder setImg(com.google.protobuf.ByteString value) {
                  copyOnWrite();
                  instance.setImg(value);
                  return this;
              }

              /**
         * <code>bytes img = 4;</code>
               */
              public Builder clearImg() {
                  copyOnWrite();
                  instance.clearImg();
                  return this;
              }

              // @@protoc_insertion_point(builder_scope:google.protobuf.TargetCells.Cell)
          }
      }

      /**
       * Protobuf type {@code google.protobuf.TargetCells}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells, Builder> implements
        // @@protoc_insertion_point(builder_implements:google.protobuf.TargetCells)
              org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCellsOrBuilder {
      // Construct using org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.newBuilder()
      private Builder() {
          super(DEFAULT_INSTANCE);
      }


          /**
           * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public java.util.List<org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell> getCellsList() {
          return java.util.Collections.unmodifiableList(
            instance.getCellsList());
      }
      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public int getCellsCount() {
          return instance.getCellsCount();
      }/**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell getCells(int index) {
        return instance.getCells(index);
      }

          /**
           * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public Builder setCells(
          int index, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell value) {
          copyOnWrite();
          instance.setCells(index, value);
          return this;
      }
      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public Builder setCells(
          int index, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell.Builder builderForValue) {
          copyOnWrite();
          instance.setCells(index, builderForValue);
          return this;
      }

          /**
           * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public Builder addCells(org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell value) {
          copyOnWrite();
          instance.addCells(value);
        return this;
      }

          /**
           * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public Builder addCells(
          int index, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell value) {
          copyOnWrite();
          instance.addCells(index, value);
        return this;
      }

          /**
           * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public Builder addCells(
          org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell.Builder builderForValue) {
          copyOnWrite();
          instance.addCells(builderForValue);
          return this;
      }
      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public Builder addCells(
          int index, org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell.Builder builderForValue) {
          copyOnWrite();
          instance.addCells(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public Builder addAllCells(
              java.lang.Iterable<? extends org.yanzhe.robomaster.recodaemon.net.proto.TargetCellsProto.TargetCells.Cell> values) {
          copyOnWrite();
          instance.addAllCells(values);
        return this;
      }
      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public Builder clearCells() {
          copyOnWrite();
          instance.clearCells();
        return this;
      }
      /**
       * <code>repeated .google.protobuf.TargetCells.Cell cells = 1;</code>
       */
      public Builder removeCells(int index) {
          copyOnWrite();
          instance.removeCells(index);
        return this;
      }

          // @@protoc_insertion_point(builder_scope:google.protobuf.TargetCells)
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
