/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tensorflow_Graph */

#ifndef _Included_org_tensorflow_Graph
#define _Included_org_tensorflow_Graph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tensorflow_Graph
 * Method:    allocate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_tensorflow_Graph_allocate
  (JNIEnv *, jclass);

/*
 * Class:     org_tensorflow_Graph
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_tensorflow_Graph_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_tensorflow_Graph
 * Method:    operation
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_tensorflow_Graph_operation
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_tensorflow_Graph
 * Method:    nextOperation
 * Signature: (JI)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_tensorflow_Graph_nextOperation
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_tensorflow_Graph
 * Method:    importGraphDef
 * Signature: (J[BLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_tensorflow_Graph_importGraphDef
  (JNIEnv *, jclass, jlong, jbyteArray, jstring);

/*
 * Class:     org_tensorflow_Graph
 * Method:    toGraphDef
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_tensorflow_Graph_toGraphDef
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
