/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tensorflow_SavedModelBundle */

#ifndef _Included_org_tensorflow_SavedModelBundle
#define _Included_org_tensorflow_SavedModelBundle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tensorflow_SavedModelBundle
 * Method:    load
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[B)Lorg/tensorflow/SavedModelBundle;
 */
JNIEXPORT jobject JNICALL Java_org_tensorflow_SavedModelBundle_load
  (JNIEnv *, jclass, jstring, jobjectArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
